#!/usr/bin/env python3
"""Compare this document's PROSE tally against the GENERATED one.

    python3 docs/audit/tally-cross-check.py     # exit 0 agree, 1 disagree, 2 cannot tell

`finalaudit.md` states its finding tally twice on purpose. Once in prose near the
top, written by hand, and once inside the `finding-index:begin/end` block, derived
from the rows by `finding-index.py`. Two independent derivations of the same
number disagree the moment either the prose or the rows move without the other,
which is the only reason to state it twice.

That cross-check has been run on every commit as a re-typed one-off, and a
re-typed comparator is a bad place for the audit's own arithmetic to live. This
one already got it wrong once: it split the prose tally on `·` without stripping
the `> ` that continues a blockquote onto a second line, so `BLOCKED 1` read as
`> BLOCKED 1` and it reported DISAGREE over a line wrap. That failure was loud and
cost a minute. The same slip in the other direction — a normaliser that smooths
away a real difference — would have been silent, and would have certified drift.

So the rule here is the one `AUDIT-008` arrived at from the other side: the
dangerous answer is not "these disagree", it is "these agree" reached without
having compared anything. Both tallies must PARSE before either is trusted, and a
pattern that fails to match is exit 2 and a named reason, never a quiet pass.
"""
import re
import sys

DOC = 'finalaudit.md'

# Both derivations, as they are actually written.
GENERATED = re.compile(
    r'Generated by `docs/audit/finding-index\.py`\. '
    r'(?P<rows>\d+) finding rows, (?P<ids>\d+) distinct ids\. (?P<tally>[^*]+)\*')
PROSE = re.compile(
    r'derives the tally from the\s*\n?>?\s*document itself: '
    r'\*\*(?P<tally>.+?)\*\* — (?P<rows>\d+) rows', re.S)


def buckets(text: str) -> dict:
    """`FIXED 76 · CHECKED 2 · …` → {'FIXED': 76, …}, order-insensitively.

    The prose tally wraps across lines inside a blockquote, so `> ` has to go
    before the split or every bucket after the wrap carries it. Comparing
    dictionaries rather than strings is deliberate: the generated side sorts its
    buckets alphabetically and the prose side lists them by importance, and a
    string compare would report a difference that is not one.
    """
    flat = re.sub(r'\n\s*>?\s*', ' ', text)
    out = {}
    for part in flat.split('·'):
        part = part.strip()
        if not part:
            continue
        # `— 4` is the generated block's own name for rows whose status could not
        # be derived, and it is a real state that has to be comparable rather than
        # fatal. The first time this script met one it exited 2 saying
        # "unparseable" — safe, but it said nothing about what had actually gone
        # wrong, which was a row opening "**Owner’s decision**" with a
        # typographic apostrophe that finding-index.py's `Owner'?s` could not match.
        m = re.fullmatch(r"(—|[A-Z][A-Z'’ ]*?)\s+(\d+)", part)
        if not m:
            raise ValueError(f'unparseable tally bucket: {part!r}')
        name = m.group(1).strip().replace('’', "'")
        out['BLANK' if name == '—' else name] = int(m.group(2))
    return out


def main() -> int:
    doc = open(DOC, encoding='utf-8').read()

    gen, prose = GENERATED.search(doc), PROSE.search(doc)
    # Neither half may be assumed. A missing prose tally with a present generated
    # one is exactly what "somebody reworded the header" looks like, and reporting
    # AGREE off one side would be agreement with nothing.
    if not gen or not prose:
        missing = ' and '.join(n for n, m in (('the generated block', gen), ('the prose tally', prose)) if not m)
        print(f'CANNOT COMPARE: {missing} did not match in {DOC}. Nothing was '
              'checked, so this is not a pass. Either the wording moved or the '
              'index was never written — fix the pattern or re-run '
              '`finding-index.py --write`.', file=sys.stderr)
        return 2

    try:
        g, p = buckets(gen.group('tally')), buckets(prose.group('tally'))
    except ValueError as exc:
        print(f'CANNOT COMPARE: {exc}. Nothing was checked.', file=sys.stderr)
        return 2
    if not g or not p:
        print('CANNOT COMPARE: a tally parsed to zero buckets, so the comparison '
              'below would be {} == {} and would pass over nothing.', file=sys.stderr)
        return 2

    g_rows, p_rows = int(gen.group('rows')), int(prose.group('rows'))
    problems = []
    if g_rows != p_rows:
        problems.append(f'row count: generated {g_rows}, prose {p_rows}')
    if sum(g.values()) != g_rows:
        problems.append(f'the generated buckets sum to {sum(g.values())} but it claims {g_rows} rows')
    for key in sorted(set(g) | set(p)):
        if g.get(key) != p.get(key):
            problems.append(f'{key}: generated {g.get(key, "absent")}, prose {p.get(key, "absent")}')

    # Named before any tally arithmetic: "N rows this parser could not classify"
    # is a different and worse fact than "the two counts differ by N", and the
    # second message would bury the first. A blank row is not a row with no
    # state — it is a row whose owner cannot act on it.
    if g.get('BLANK'):
        problems.insert(0, f"{g['BLANK']} row(s) indexed BLANK — the status patterns in "
                           'finding-index.py did not recognise how those rows open. Read '
                           'the row and add a pattern for the words it already uses; do '
                           'not reword the row to fit a pattern, and do not leave it.')

    if problems:
        print('TALLIES DISAGREE:')
        for line in problems:
            print(f'  - {line}')
        print(f'\nThe prose near the top of {DOC} and the generated block are two '
              'derivations of one number. Re-run `python3 docs/audit/finding-index.py '
              '--write`, then correct the prose to match the block — the block is '
              'derived from the rows, the prose is typed.', file=sys.stderr)
        return 1

    print(f'tallies agree: {g_rows} rows · ' + ' · '.join(f'{k} {v}' for k, v in sorted(g.items())))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
