import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';
import {test,expect,type Page} from '@playwright/test';
import {reactBrowserScripts} from './helpers/react-browser';

// Actual React19/module/shared controls/dialog behavior/CSS/query hook/SDK.
// Auth/context/cache/realtime/AI/date formatter remain inert. Synthetic only.
const sourceRoot=process.env.BUBALY_ANNOUNCEMENTS_SOURCE_ROOT||process.cwd();
const {react,reactDom}=reactBrowserScripts();
const icons=fs.readFileSync(path.join(path.dirname(require.resolve('lucide-react/package.json')),'dist/umd/lucide-react.min.js'),'utf8');
const sdk=fs.readFileSync(path.join(path.dirname(require.resolve('@supabase/supabase-js/package.json')),'dist/umd/supabase.js'),'utf8');
const isolated=new Set(['react','react-dom','lucide-react','next/navigation','next/link','@/components/app/app-context','@/components/i18n/locale-provider','@/components/i18n/use-format','@/components/ui/toast','@/lib/supabase/client','@/lib/offline/cache','@/lib/offline/cache-scope','@/lib/realtime/published-tables','@/components/ai/ai-insight','@/lib/utils/format']);
const modules:Record<string,{source:string,imports:Record<string,string>}>= {};
function collect(filename:string):string{const id=path.resolve([filename,filename+'.ts',filename+'.tsx',path.join(filename,'index.ts')].find(f=>fs.existsSync(f)&&fs.statSync(f).isFile())??filename);if(modules[id])return id;const raw=fs.readFileSync(id,'utf8');const source=ts.transpileModule(raw,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React}}).outputText;const item=modules[id]={source,imports:{} as Record<string,string>};for(const match of source.matchAll(/require\(["']([^"']+)["']\)/g)){const name=match[1];item.imports[name]=isolated.has(name)?name:collect(name.startsWith('@/')?path.join(sourceRoot,name.slice(2)):name.startsWith('.')?path.resolve(path.dirname(id),name):require.resolve(name,{paths:[path.dirname(id)]}));}return id;}
const entry=collect(path.join(sourceRoot,'components/modules/announcements-module.tsx'));
let css='';test.beforeAll(async()=>{const config={exports:{} as any};new Function('module','exports','require',ts.transpileModule(fs.readFileSync(path.join(sourceRoot,'tailwind.config.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(config,config.exports,require);config.exports.default.content=[path.join(sourceRoot,'components/**/*.{ts,tsx}')];css=(await postcss([tailwindcss(config.exports.default),autoprefixer()]).process(fs.readFileSync(path.join(sourceRoot,'app/globals.css'),'utf8'),{from:path.join(sourceRoot,'app/globals.css')})).css;});
const diagnostics=new WeakMap<Page,string[]>();
test.beforeEach(({page})=>{const errors:string[]=[];diagnostics.set(page,errors);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(['warning','error'].includes(m.type()))errors.push(m.type()+': '+m.text())});page.on('requestfailed',r=>errors.push(r.url()));});
test.afterEach(async({page})=>{const proof=await page.evaluate(()=>{const p=(window as any).__announcements;return{requests:p.requests,store:p.store,toasts:p.toasts,forbidden:p.forbidden,settled:p.settled,maxPosts:p.maxPosts,requestBudget:p.requestBudget};});await test.info().attach('synthetic SDK composer receipt',{body:JSON.stringify(proof),contentType:'application/json'});expect(proof.forbidden).toEqual([]);expect(proof.requests.length).toBeLessThanOrEqual(proof.requestBudget);expect(proof.requests.filter((r:any)=>r.method==='POST').length).toBeLessThanOrEqual(proof.maxPosts);expect(diagnostics.get(page)).toEqual([]);});
async function fixture(page:Page,mode='success',options:{maxPosts?:number;modes?:string[];requestBudget?:number;strict?:boolean}={}){
 await page.route('**/*',async route=>{if(route.request().url()!=='https://announcements-fixture.invalid/')throw Error('Unexpected native request '+route.request().url());await route.fulfill({contentType:'text/html',body:'<!doctype html><html><body><main id="root"></main></body></html>'});});
 await page.goto('https://announcements-fixture.invalid/');await page.addStyleTag({content:css});for(const content of [react,reactDom,'window.react=window.React;',icons,sdk])await page.addScriptTag({content});
 const messages=JSON.parse(fs.readFileSync(path.join(sourceRoot,'lib/i18n/messages/en-US.json'),'utf8'));
 await page.evaluate(({sources,entry,messages,mode,options})=>{
  const w=window as any,R=w.React,D=w.ReactDOM,p:any=w.__announcements={requests:[],store:[],toasts:[],forbidden:[],settled:0,familyId:'family-A',userId:'user-A',mode,modes:[mode,...(options.modes??[])],releases:[],maxPosts:options.maxPosts??1,requestBudget:options.requestBudget??6};
  const deny=(name:string)=>(...args:any[])=>{p.forbidden.push(name);throw Error('Outside ordinary composer fixture '+name);};
  const response=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});
  const transport=async(input:any,options:any={})=>{const url=new URL(String(input)),table=url.pathname.split('/').pop(),method=options.method??'GET';if(url.origin!=='https://announcements-store.invalid'||!['family_announcements','announcement_reads'].includes(table??'')||!['GET','POST'].includes(method))return deny('SDK transport '+method+' '+url)();if(p.requests.length>=p.requestBudget)return deny('request bound')();p.requests.push({table,method,query:url.search,body:options.body?JSON.parse(options.body):null});if(method==='GET')return response(table==='family_announcements'?p.store.filter((r:any)=>url.searchParams.get('family_id')==='eq.'+r.family_id):[]);if(table!=='family_announcements'||p.requests.filter((r:any)=>r.method==='POST').length>p.maxPosts)return deny('nonordinary write')();const postIndex=p.requests.filter((r:any)=>r.method==='POST').length;const operationMode=p.modes[postIndex-1]??p.mode;if(operationMode.startsWith('held')){p.held=true;await new Promise<void>(resolve=>{p.releases[postIndex-1]=resolve;p.release=resolve;});}p.settled++;if(operationMode.includes('throw'))throw Error('Synthetic announcement transport lost');if(operationMode.includes('error'))return response({message:'Synthetic announcement refused'},500);const row={id:postIndex===1?'synthetic-post-A':'synthetic-post-'+postIndex,...JSON.parse(options.body)};p.store.push(row);return response(null,201);};
  const db=w.supabase.createClient('https://announcements-store.invalid','synthetic-public-key',{global:{fetch:transport},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});db.channel=deny('realtime subscription');db.removeChannel=deny('realtime removal');
  const tr=(key:string,args:any={})=>Object.entries(args).reduce((s,[k,v])=>s.split('{'+k+'}').join(String(v)),messages[key]||key);
  const mocks:Record<string,any>={react:R,'react-dom':D,'lucide-react':w.LucideReact,'next/navigation':{useRouter:()=>({push:deny('navigation'),refresh:deny('route refresh')})},'next/link':{default:(props:any)=>R.createElement('a',props,props.children)},'@/components/app/app-context':{useApp:()=>({familyId:p.familyId,userId:p.userId,role:'parent',members:[],selfMember:null})},'@/components/i18n/locale-provider':{useTranslations:()=>tr,useLocale:()=>({code:'en-US'}),usePlural:()=>((key:string,n:number)=>n+' items')},'@/components/i18n/use-format':{useFormat:()=>({fmtDateTime:deny('date format')})},'@/components/ui/toast':{useToast:()=>({success:(text:string)=>p.toasts.push(['success',text]),error:(text:string)=>p.toasts.push(['error',text])})},'@/lib/supabase/client':{createClient:()=>db},'@/lib/offline/cache-scope':{useAuthenticatedCacheScope:()=>null,isAuthenticatedCacheScopeCurrent:()=>true},'@/lib/offline/cache':{cacheKey:(table:string,family:string)=>table+':'+family,getCacheGeneration:()=>0,subscribeCacheInvalidation:()=>()=>{},cacheIdentity:deny('cache identity'),readPartitionedCache:deny('cache read'),writePartitionedCache:deny('cache write')},'@/lib/realtime/published-tables':{realtimeChannelFor:()=>null},'@/components/ai/ai-insight':{AiInsight:()=>null},'@/lib/utils/format':{initials:(s:string)=>s.slice(0,1)}};
  const loaded:Record<string,any>={};function load(id:string):any{if(id in mocks)return mocks[id];if(loaded[id])return loaded[id].exports;const item=sources[id];if(!item)throw Error('Unexpected module '+id);const m=loaded[id]={exports:{}};new Function('require','module','exports',item.source)((name:string)=>load(item.imports[name]),m,m.exports);return m.exports;}
  const root=D.createRoot(document.getElementById('root'));p.render=()=>root.render(options.strict?R.createElement(R.StrictMode,null,R.createElement(load(entry).AnnouncementsModule)):R.createElement(load(entry).AnnouncementsModule));p.unmount=()=>root.unmount();p.render();
 },{sources:modules,entry,messages,mode,options});
 await expect(page.getByText('No announcements yet',{exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>(window as any).__announcements.requests.length)).toBe(options.strict?4:2);
}
async function draft(page:Page,title='Synthetic A title',body='Synthetic A details',pin=false){await page.getByRole('button',{name:'New',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('textbox',{name:'Title',exact:true}).fill(title);await page.getByLabel('Details',{exact:true}).fill(body);await page.getByLabel('Pin to top',{exact:true}).setChecked(pin);}
async function begin(page:Page){await page.getByRole('button',{name:'Post',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__announcements.requests.filter((r:any)=>r.method==='POST').length)).toBe(1);}
async function release(page:Page){await page.evaluate(()=>(window as any).__announcements.release());await expect.poll(()=>page.evaluate(()=>(window as any).__announcements.settled)).toBe(1);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));}
async function newer(page:Page){await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await draft(page,'Synthetic B title','Synthetic B details',true);}
async function preserved(page:Page){await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('textbox',{name:'Title',exact:true})).toHaveValue('Synthetic B title');await expect(page.getByLabel('Details',{exact:true})).toHaveValue('Synthetic B details');await expect(page.getByLabel('Pin to top',{exact:true})).toBeChecked();await expect(page.getByRole('button',{name:'Post',exact:true})).toBeEnabled();}
test('ordinary current compose success persists the submitted composition and closes',async({page})=>{await fixture(page);await draft(page,'Synthetic A title','Synthetic A details',true);await begin(page);await expect(page.getByRole('dialog')).toHaveCount(0);const p=await page.evaluate(()=>({store:(window as any).__announcements.store,toasts:(window as any).__announcements.toasts}));expect(p.store).toEqual([{id:'synthetic-post-A',family_id:'family-A',author_id:'user-A',author_member_id:null,title:'Synthetic A title',body:'Synthetic A details',is_pinned:true}]);expect(p.toasts).toEqual([['success','Announcement posted']]);});
test('ordinary current compose HTTP500 refusal preserves the draft and reenables Post',async({page})=>{await fixture(page,'error');await draft(page,'Synthetic A title','Synthetic A details',true);await begin(page);await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('button',{name:'Post',exact:true})).toBeEnabled();await expect(page.getByRole('textbox',{name:'Title',exact:true})).toHaveValue('Synthetic A title');await expect(page.getByLabel('Details',{exact:true})).toHaveValue('Synthetic A details');await expect(page.getByLabel('Pin to top',{exact:true})).toBeChecked();expect(await page.evaluate(()=>(window as any).__announcements.store)).toEqual([]);expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([['error','Synthetic announcement refused']]);});
test('an unsent cancelled composer dispatches no POST',async({page})=>{await fixture(page);await draft(page);await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__announcements.requests.map((r:any)=>r.method))).toEqual(['GET','GET']);expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([]);});
test('a whitespace-only title performs no POST and keeps the composer usable',async({page})=>{await fixture(page);await draft(page,'   ','Synthetic A details');await page.getByRole('button',{name:'Post',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('button',{name:'Post',exact:true})).toBeEnabled();expect(await page.evaluate(()=>(window as any).__announcements.requests.map((r:any)=>r.method))).toEqual(['GET','GET']);expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([]);});
test('held old compose success cannot clear or close a newly reopened draft',async({page})=>{await fixture(page,'held-success');await draft(page);await begin(page);await newer(page);await release(page);expect(await page.evaluate(()=>(window as any).__announcements.store[0].title)).toBe('Synthetic A title');await preserved(page);expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([]);});
test('held old compose HTTP500 refusal cannot send feedback into a newly reopened draft',async({page})=>{await fixture(page,'held-error');await draft(page);await begin(page);await newer(page);await release(page);await preserved(page);expect(await page.evaluate(()=>(window as any).__announcements.store)).toEqual([]);expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([]);});
test('unmount before held success fences stale feedback while the original POST completes',async({page})=>{await fixture(page,'held-success');await draft(page);await begin(page);await page.evaluate(()=>(window as any).__announcements.unmount());await release(page);expect(await page.evaluate(()=>(window as any).__announcements.store[0].title)).toBe('Synthetic A title');expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([]);await expect(page.getByRole('dialog')).toHaveCount(0);});
test('held old-family success cannot clear a newly opened current-family draft',async({page})=>{await fixture(page,'held-success');await draft(page);await begin(page);await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.evaluate(()=>{const p=(window as any).__announcements;p.familyId='family-B';p.userId='user-B';p.render();});await expect.poll(()=>page.evaluate(()=>(window as any).__announcements.requests.filter((r:any)=>r.method==='GET').length)).toBe(4);await draft(page,'Synthetic B title','Synthetic B details',true);await release(page);expect(await page.evaluate(()=>(window as any).__announcements.store[0].family_id)).toBe('family-A');await preserved(page);expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([]);});
for(const method of ['Escape','backdrop'] as const)test(method+' close fences a held old success from the reopened draft',async({page})=>{await fixture(page,'held-success');await draft(page);await begin(page);if(method==='Escape')await page.keyboard.press('Escape');else await page.locator('.overlay-scrim').click({position:{x:5,y:5}});await expect(page.getByRole('dialog')).toHaveCount(0);await draft(page,'Synthetic B title','Synthetic B details',true);await release(page);expect(await page.evaluate(()=>(window as any).__announcements.store[0].title)).toBe('Synthetic A title');await preserved(page);expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([]);});
test('same open composer edits made after POST dispatch survive the older success',async({page})=>{await fixture(page,'held-success');await draft(page);await begin(page);await expect(page.getByRole('textbox',{name:'Title',exact:true})).toBeEnabled();await expect(page.getByLabel('Details',{exact:true})).toBeEnabled();await expect(page.getByLabel('Pin to top',{exact:true})).toBeEnabled();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Synthetic B title');await page.getByLabel('Details',{exact:true}).fill('Synthetic B details');await page.getByLabel('Pin to top',{exact:true}).check();await release(page);expect(await page.evaluate(()=>(window as any).__announcements.store[0].title)).toBe('Synthetic A title');await preserved(page);});


async function releaseAt(page:Page,index:number,count:number){await page.evaluate(index=>(window as any).__announcements.releases[index](),index);await expect.poll(()=>page.evaluate(()=>(window as any).__announcements.settled)).toBe(count);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));}
async function submitEvent(page:Page){await page.getByRole('dialog').locator('form').evaluate(form=>form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));}
for(const field of ['title','details','pin'] as const)test(field+' edit and reversion still owns an unsaved draft after older success',async({page})=>{await fixture(page,'held-success');await draft(page);await begin(page);if(field==='title'){await page.getByRole('textbox',{name:'Title',exact:true}).fill('Synthetic changed title');await page.getByRole('textbox',{name:'Title',exact:true}).fill('Synthetic A title');}else if(field==='details'){await page.getByLabel('Details',{exact:true}).fill('Synthetic changed details');await page.getByLabel('Details',{exact:true}).fill('Synthetic A details');}else{await page.getByLabel('Pin to top',{exact:true}).check();await page.getByLabel('Pin to top',{exact:true}).uncheck();}await release(page);await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('textbox',{name:'Title',exact:true})).toHaveValue('Synthetic A title');await expect(page.getByLabel('Details',{exact:true})).toHaveValue('Synthetic A details');await expect(page.getByLabel('Pin to top',{exact:true})).not.toBeChecked();await expect(page.getByRole('button',{name:'Post',exact:true})).toBeEnabled();expect(await page.evaluate(()=>(window as any).__announcements.store[0].title)).toBe('Synthetic A title');expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([]);});
test('context A to B to A cannot revive an older composer owner',async({page})=>{await fixture(page,'held-success',{requestBudget:8});await draft(page);await begin(page);await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.evaluate(()=>{const p=(window as any).__announcements;p.familyId='family-B';p.userId='user-B';p.render();});await expect.poll(()=>page.evaluate(()=>(window as any).__announcements.requests.filter((r:any)=>r.method==='GET').length)).toBe(4);await page.evaluate(()=>{const p=(window as any).__announcements;p.familyId='family-A';p.userId='user-A';p.render();});await expect.poll(()=>page.evaluate(()=>(window as any).__announcements.requests.filter((r:any)=>r.method==='GET').length)).toBe(6);await draft(page,'Synthetic B title','Synthetic B details',true);await release(page);await preserved(page);expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([]);});
test('StrictMode setup keeps the current composer able to finish normally',async({page})=>{await fixture(page,'success',{strict:true});await draft(page);await begin(page);await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__announcements.store[0].title)).toBe('Synthetic A title');expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([['success','Announcement posted']]);});
test('current HTTP500 refusal releases only its own busy state for a successful retry',async({page})=>{await fixture(page,'error',{maxPosts:2,modes:['success']});await draft(page);await begin(page);await expect(page.getByRole('button',{name:'Post',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Post',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__announcements.settled)).toBe(2);await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__announcements.store.map((r:any)=>r.title))).toEqual(['Synthetic A title']);expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([['error','Synthetic announcement refused'],['success','Announcement posted']]);});
test('current synthetic SDK fetch throw leaves a usable draft with one error receipt',async({page})=>{await fixture(page,'throw');await draft(page);await begin(page);await expect(page.getByRole('button',{name:'Post',exact:true})).toBeEnabled();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('textbox',{name:'Title',exact:true})).toHaveValue('Synthetic A title');expect(await page.evaluate(()=>(window as any).__announcements.store)).toEqual([]);const toasts=await page.evaluate(()=>(window as any).__announcements.toasts);expect(toasts).toHaveLength(1);expect(toasts[0][0]).toBe('error');});
test('two immediate synthetic form submit events dispatch only one ordinary POST',async({page})=>{await fixture(page,'held-success',{maxPosts:2,modes:['held-success']});await draft(page);await submitEvent(page);await submitEvent(page);expect(await page.evaluate(()=>(window as any).__announcements.requests.filter((r:any)=>r.method==='POST').length)).toBe(1);await releaseAt(page,0,1);await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__announcements.store)).toHaveLength(1);});
for(const oldMode of ['held-success','held-error'])test(oldMode+' completion cannot release a newer pending POST or affect its draft',async({page})=>{await fixture(page,oldMode,{maxPosts:2,modes:['held-success']});await draft(page);await begin(page);await newer(page);await submitEvent(page);await expect.poll(()=>page.evaluate(()=>(window as any).__announcements.requests.filter((r:any)=>r.method==='POST').length)).toBe(2);await releaseAt(page,0,1);await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('textbox',{name:'Title',exact:true})).toHaveValue('Synthetic B title');await expect(page.getByLabel('Details',{exact:true})).toHaveValue('Synthetic B details');await expect(page.getByLabel('Pin to top',{exact:true})).toBeChecked();await expect(page.getByRole('button',{name:'Post',exact:true})).toBeDisabled();expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([]);await releaseAt(page,1,2);await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__announcements.store.map((r:any)=>r.title))).toEqual(oldMode==='held-success'?['Synthetic A title','Synthetic B title']:['Synthetic B title']);expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([['success','Announcement posted']]);});
test('unsent Cancel retains the title details and pin state when reopened',async({page})=>{await fixture(page);await draft(page,'Synthetic B title','Synthetic B details',true);await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'New',exact:true}).click();await preserved(page);expect(await page.evaluate(()=>(window as any).__announcements.requests.map((r:any)=>r.method))).toEqual(['GET','GET']);});
test('same open edited draft can submit its own composition after older success settles',async({page})=>{await fixture(page,'held-success',{maxPosts:2,modes:['success']});await draft(page);await begin(page);await page.getByRole('textbox',{name:'Title',exact:true}).fill('Synthetic B title');await page.getByLabel('Details',{exact:true}).fill('Synthetic B details');await page.getByLabel('Pin to top',{exact:true}).check();await releaseAt(page,0,1);await preserved(page);await page.getByRole('button',{name:'Post',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__announcements.settled)).toBe(2);await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__announcements.store.map((r:any)=>[r.title,r.body,r.is_pinned]))).toEqual([['Synthetic A title','Synthetic A details',false],['Synthetic B title','Synthetic B details',true]]);expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([['success','Announcement posted']]);});
for(const context of ['familyId','userId'] as const)test(context+' A to B to A while open fences an older pending owner and permits the new draft POST',async({page})=>{await fixture(page,'held-success',{maxPosts:2,modes:['success'],requestBudget:8});await draft(page);await begin(page);await page.evaluate(context=>{const p=(window as any).__announcements;p[context]=context==='familyId'?'family-B':'user-B';p.render();},context);if(context==='familyId')await expect.poll(()=>page.evaluate(()=>(window as any).__announcements.requests.filter((r:any)=>r.method==='GET').length)).toBe(4);else await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await expect(page.getByRole('button',{name:'Post',exact:true})).toBeEnabled();await page.evaluate(context=>{const p=(window as any).__announcements;p[context]=context==='familyId'?'family-A':'user-A';p.render();},context);if(context==='familyId')await expect.poll(()=>page.evaluate(()=>(window as any).__announcements.requests.filter((r:any)=>r.method==='GET').length)).toBe(6);else await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await page.getByRole('textbox',{name:'Title',exact:true}).fill('Synthetic B title');await page.getByLabel('Details',{exact:true}).fill('Synthetic B details');await page.getByLabel('Pin to top',{exact:true}).check();await releaseAt(page,0,1);await preserved(page);expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([]);await page.getByRole('button',{name:'Post',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__announcements.settled)).toBe(2);await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__announcements.store.map((r:any)=>[r.title,r.family_id,r.author_id]))).toEqual([['Synthetic A title','family-A','user-A'],['Synthetic B title','family-A','user-A']]);expect(await page.evaluate(()=>(window as any).__announcements.toasts)).toEqual([['success','Announcement posted']]);});
