import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';
import {expect,test,type Page} from '@playwright/test';
import {reactBrowserScripts} from './helpers/react-browser';

// Actual Inventory browsing/shared UI/CSS/query hook/SDK GETs with synthetic rows.
// Media/storage/weather/recommendations/cost/date and app/cache context are inert.
// No writes, Auth, RLS, provider, hosted backend or full Inventory proof.
const sourceRoot=process.env.BUBALY_INVENTORY_UI_SOURCE_ROOT||process.cwd();
const diagnostics=new WeakMap<Page,string[]>();
test.beforeEach(async({page})=>{const errors:string[]=[];diagnostics.set(page,errors);page.on('console',m=>{if(['warning','error'].includes(m.type()))errors.push(m.type()+': '+m.text());});page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url()));});
test.afterEach(async({page})=>{expect(diagnostics.get(page)).toEqual([]);expect(await page.evaluate(()=>(window as any).__inventory.errors)).toEqual([]);});
const {react,reactDom}=reactBrowserScripts();
const icons=fs.readFileSync(path.join(path.dirname(require.resolve('lucide-react/package.json')),'dist/umd/lucide-react.min.js'),'utf8');
const sdk=fs.readFileSync(path.join(path.dirname(require.resolve('@supabase/supabase-js/package.json')),'dist/umd/supabase.js'),'utf8');
const isolated=new Set(['react','react-dom','lucide-react','next/navigation','next/link','@/components/app/app-context','@/components/i18n/locale-provider','@/components/i18n/use-format','@/components/ui/toast','@/lib/supabase/client','@/lib/offline/cache-scope','@/lib/storage/family-media','@/lib/weather/open-meteo','@/lib/inventory/finder','@/lib/wallet/ledger','@/components/ui/confirm','@/lib/closet/wear','@/components/media/family-media-img','@/components/ai/ai-insight']);
const modules:Record<string,{source:string;imports:Record<string,string>}>= {};
function collect(filename:string):string {
 const id=path.resolve([filename,filename+'.ts',filename+'.tsx',path.join(filename,'index.ts')].find(f=>fs.existsSync(f)&&fs.statSync(f).isFile())??filename);
 if(modules[id])return id;
 const raw=fs.readFileSync(id,'utf8');
 const source=/\.tsx?$/.test(id)?ts.transpileModule(raw,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React}}).outputText:raw;
 const item=modules[id]={source,imports:{} as Record<string,string>};
 for(const match of source.matchAll(/require\(["']([^"']+)["']\)/g)){const name=match[1];if(isolated.has(name)){item.imports[name]=name;continue;}item.imports[name]=collect(name.startsWith('@/')?path.join(sourceRoot,name.slice(2)):name.startsWith('.')?path.resolve(path.dirname(id),name):require.resolve(name,{paths:[path.dirname(id)]}));}
 return id;
}
const entry=collect(path.join(sourceRoot,'components/modules/inventory-module.tsx'));
let css='';
test.beforeAll(async()=>{const config={exports:{} as any};const code=ts.transpileModule(fs.readFileSync(path.join(sourceRoot,'tailwind.config.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;new Function('module','exports','require',code)(config,config.exports,require);config.exports.default.content=[path.join(sourceRoot,'components/**/*.{ts,tsx}'),path.join(sourceRoot,'app/**/*.{ts,tsx}')];css=(await postcss([tailwindcss(config.exports.default),autoprefixer()]).process(fs.readFileSync(path.join(sourceRoot,'app/globals.css'),'utf8'),{from:path.join(sourceRoot,'app/globals.css')})).css;});
const finderCode=ts.transpileModule(fs.readFileSync(path.join(sourceRoot,'lib/inventory/finder.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
async function fixture(page:Page,count=121,withLocation=false){
 await page.route('**/*',async route=>{if(route.request().url()!=='https://inventory-fixture.invalid/')throw Error('Unexpected native request '+route.request().url());await route.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body><main id="root"></main></body></html>'});});
 await page.goto('https://inventory-fixture.invalid/');await page.addStyleTag({content:css});for(const content of [react,reactDom,'window.react=window.React;',icons,sdk])await page.addScriptTag({content});
 const messages=JSON.parse(fs.readFileSync(path.join(sourceRoot,'lib/i18n/messages/en-US.json'),'utf8'));
 await page.evaluate(({sources,entry,messages,count,finderCode,withLocation})=>{
  const w=window as any,R=w.React,D=w.ReactDOM,p:any=w.__inventory={errors:[] as string[],requests:[] as any[],forbidden:[] as string[],familyId:'family-A',userId:'user-A'};
  window.addEventListener('error',e=>p.errors.push(e.message));window.addEventListener('unhandledrejection',e=>{p.errors.push(String(e.reason));e.preventDefault();});
  const deny=(name:string)=>(...args:any[])=>{p.forbidden.push(name);throw Error('Outside ordinary browsing fixture: '+name);},fail=deny('nonordinary operation');
  const respond=(body:any)=>new Response(JSON.stringify(body),{status:200,headers:{'content-type':'application/json'}});
  p.store=Array.from({length:count},(_,index)=>({id:'item-'+(index+1),name:'Catalog item '+String(index+1).padStart(3,'0'),family_id:'family-A',updated_at:String(index+1).padStart(4,'0'),category:'tools',status:'in_place',quantity:1,location_id:withLocation?'room-A':null,owner_member_id:null,photo_path:null,value_cents:null,brand:null,model:null,serial_number:null,tags:[],lent_to:null,lent_on:null,warranty_until:null}));
  const transport=async(input:any,options:any={})=>{
   const url=new URL(String(input)),table=url.pathname.split('/').pop(),method=options.method??'GET';
   if(url.origin!=='https://inventory-store.invalid'||!['inventory_items','home_locations','inventory_moves'].includes(table??'')||method!=='GET')return deny('SDK transport '+method+' '+url)();
   p.requests.push({table,method,query:url.search});if(table!=='inventory_items')return respond(table==='home_locations'&&withLocation?[{id:'room-A',name:'Workshop',kind:'room',parent_id:null,family_id:p.familyId}]:[]);
   let rows=p.store.filter((row:any)=>[...url.searchParams].every(([key,value])=>!value.startsWith('eq.')||String(row[key])===value.slice(3)));
   const order=url.searchParams.get('order');if(order){const keys=order.split(',');rows=[...rows].sort((a:any,b:any)=>{for(const item of keys){const [key,direction]=item.split('.');if(a[key]<b[key])return direction==='desc'?1:-1;if(a[key]>b[key])return direction==='desc'?-1:1;}return 0;});}
   const offset=Number(url.searchParams.get('offset')||0),limit=url.searchParams.get('limit');rows=rows.slice(offset,limit?offset+Number(limit):undefined);p.delivered=rows.length;return respond(rows);
  };
  const db=w.supabase.createClient('https://inventory-store.invalid','synthetic-public-key',{global:{fetch:transport},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});db.channel=()=>({on(){return this;},subscribe(){return this;}});db.removeChannel=async()=>{};
  const tr=(key:string,vars:Record<string,unknown>={})=>Object.entries(vars).reduce((s,[k,v])=>s.split('{'+k+'}').join(String(v)),messages[key]||key);
  const finder={exports:{} as any};new Function('module','exports',finderCode)(finder,finder.exports);
  const ordinaryFinder={...finder.exports,lentOut:()=>[],warrantyAlerts:()=>[],valueSummary:()=>({valuedItems:0,totalCents:0,byCategory:[]}),inventorySummary:()=>({text:'Ordinary catalog fixture',rooms:0,unlocated:count,overdueLoans:0}),lastConfirmed:()=>null,dayDiff:deny('date difference')};
  const mocks:Record<string,any>={react:R,'react-dom':D,'lucide-react':w.LucideReact,'next/navigation':{useRouter:()=>({push:fail,refresh:fail})},'next/link':{default:(props:any)=>R.createElement('a',props,props.children)},'@/components/app/app-context':{useApp:()=>({familyId:p.familyId,userId:p.userId,role:'parent',members:[],selfMember:null})},'@/components/i18n/locale-provider':{useTranslations:()=>tr,useLocale:()=>({code:'en-US'}),usePlural:()=>((key:string,n:number)=>n+' items')},'@/components/i18n/use-format':{useFamilyClock:()=>({todayKey:deny('family day')}),useFamilyCalendarToday:()=>null,useFormat:()=>({fmtDate:deny('date format')})},'@/components/ui/toast':{useToast:()=>({success:deny('write success'),error:deny('write error')})},'@/lib/supabase/client':{createClient:()=>db},'@/lib/offline/cache-scope':{useAuthenticatedCacheScope:()=>null,isAuthenticatedCacheScopeCurrent:()=>true},'@/lib/storage/family-media':{familyMediaPath:deny('storage')},'@/lib/inventory/finder':ordinaryFinder,'@/lib/wallet/ledger':{formatCents:deny('money')},'@/components/ui/confirm':{useConfirm:()=>deny('confirmation/write')},'@/components/media/family-media-img':{FamilyMediaImg:({fallback}:any)=>fallback},'@/components/ai/ai-insight':{AiInsight:()=>null}};
  const loaded:Record<string,any>={};function load(id:string):any{if(id in mocks)return mocks[id];if(loaded[id])return loaded[id].exports;const item=sources[id];if(!item)throw Error('Unexpected module '+id);const m=loaded[id]={exports:{}};new Function('require','module','exports',item.source)((name:string)=>load(item.imports[name]),m,m.exports);return m.exports;}
  const root=D.createRoot(document.getElementById('root'));p.render=()=>root.render(R.createElement(load(entry).InventoryModule));p.render();
 },{sources:modules,entry,messages,count,finderCode,withLocation});
 await expect(page.getByText(count+' items',{exact:true})).toBeVisible();
}
const itemNames=(page:Page)=>page.locator('p.font-medium').filter({hasText:/^Catalog item \d{3}$/});
test.afterEach(async({page})=>{expect(await page.evaluate(()=>(window as any).__inventory.forbidden)).toEqual([]);});
test('a 120-item catalog renders its final item in the ordinary browse view',async({page})=>{await fixture(page,120);await expect(itemNames(page)).toHaveCount(120);await expect(page.getByText('Catalog item 001',{exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).__inventory.delivered)).toBe(120);});
test('a fully loaded 121-item catalog lets a user browse the final item',async({page})=>{await fixture(page,121);expect(await page.evaluate(()=>(window as any).__inventory.delivered)).toBe(121);await expect(page.getByText('121 items',{exact:true})).toBeVisible();await expect(page.getByText('Catalog item 121',{exact:true})).toBeVisible();await clickMore(page);await expect(page.getByText('Catalog item 001',{exact:true})).toBeVisible();});
test('search can still locate the loaded item omitted from the unfiltered tail',async({page})=>{await fixture(page,121);await page.getByRole('textbox').first().fill('Catalog item 001');await expect(page.getByText('1 items',{exact:true})).toBeVisible();await expect(page.getByText('Catalog item 001',{exact:true})).toHaveCount(2);await expect(itemNames(page)).toHaveCount(1);expect(await page.evaluate(()=>(window as any).__inventory.requests.filter((r:any)=>r.table==='inventory_items').length)).toBe(1);});
test('an unmatched search uses the filter-empty guidance rather than first-item guidance',async({page})=>{await fixture(page,121);await page.getByRole('textbox').first().fill('Unstored wrench');await expect(page.getByText('0 items',{exact:true})).toBeVisible();await expect(itemNames(page)).toHaveCount(0);await expect(page.getByRole('button',{name:'Add the first item',exact:true})).toHaveCount(0);});
test('an actually empty catalog keeps first-item guidance available',async({page})=>{await fixture(page,0);await expect(itemNames(page)).toHaveCount(0);await expect(page.getByRole('button',{name:'Add the first item',exact:true})).toBeEnabled();});
const more=(page:Page)=>page.getByRole('button',{name:'More',exact:true});
async function clickMore(page:Page){await expect(more(page)).toBeVisible();await more(page).click();}
async function expanded(page:Page){await fixture(page,241);await clickMore(page);await expect(itemNames(page)).toHaveCount(240);}
test('keyboard continuation reveals bounded batches and disappears at the full count',async({page})=>{await fixture(page,241);await expect(itemNames(page)).toHaveCount(120);const target=await more(page).getAttribute('aria-controls',{timeout:1500});expect(target).toBeTruthy();expect(await page.locator('[id]').evaluateAll((nodes,target)=>nodes.some(node=>node.id===target),target)).toBe(true);await more(page).focus({timeout:1500});await page.keyboard.press('Enter');await expect(itemNames(page)).toHaveCount(240);await expect(page.getByText('Catalog item 001',{exact:true})).toHaveCount(0);await more(page).focus({timeout:1500});await page.keyboard.press('Space');await expect(itemNames(page)).toHaveCount(241);await expect(page.getByText('Catalog item 001',{exact:true})).toBeVisible();await expect(more(page)).toHaveCount(0);await expect(page.getByText('241 items',{exact:true})).toBeVisible();});
test('changing and clearing a search resets expansion even when it still matches every item',async({page})=>{await expanded(page);await page.getByRole('textbox').first().fill('Catalog item');await expect(itemNames(page)).toHaveCount(120);await clickMore(page);await expect(itemNames(page)).toHaveCount(240);await page.getByRole('textbox').first().fill('');await expect(itemNames(page)).toHaveCount(120);await expect(more(page)).toBeEnabled();});
for(const [label,value] of [['Category','tools'],['Status','in_place']])test(label+' changes and restores reset expansion for the new filter instance',async({page})=>{await expanded(page);await page.getByLabel(label,{exact:true}).selectOption(value);await expect(itemNames(page)).toHaveCount(120);await clickMore(page);await expect(itemNames(page)).toHaveCount(240);await page.getByLabel(label,{exact:true}).selectOption('all');await expect(itemNames(page)).toHaveCount(120);await expect(page.getByText('241 items',{exact:true})).toBeVisible();});
test('location changes and All items restore a bounded first batch',async({page})=>{await fixture(page,241,true);await clickMore(page);await expect(itemNames(page)).toHaveCount(240);await page.getByRole('button',{name:/^🚪 Workshop/}).click();await expect(itemNames(page)).toHaveCount(120);await clickMore(page);await expect(itemNames(page)).toHaveCount(240);await page.getByRole('button',{name:'All items',exact:true}).click();await expect(itemNames(page)).toHaveCount(120);});
test('synthetic user and family context changes including returning to an old family reset expansion',async({page})=>{await expanded(page);await page.evaluate(()=>{const p=(window as any).__inventory;p.userId='user-B';p.render();});await expect(itemNames(page)).toHaveCount(120);await clickMore(page);await expect(itemNames(page)).toHaveCount(240);await page.evaluate(()=>{const p=(window as any).__inventory;p.familyId='family-B';p.store.forEach((row:any)=>row.family_id='family-B');p.render();});await expect(itemNames(page)).toHaveCount(120);await clickMore(page);await expect(itemNames(page)).toHaveCount(240);await page.evaluate(()=>{const p=(window as any).__inventory;p.familyId='family-A';p.store.forEach((row:any)=>row.family_id='family-A');p.render();});await expect(itemNames(page)).toHaveCount(120);expect(await page.evaluate(()=>(window as any).__inventory.requests.filter((r:any)=>r.table==='inventory_items').length)).toBe(3);});
test('a successful ordinary reread preserves an expanded current filter and dispatches no writes',async({page})=>{await expanded(page);await page.evaluate(()=>window.dispatchEvent(new Event('online')));await expect.poll(()=>page.evaluate(()=>(window as any).__inventory.requests.filter((r:any)=>r.table==='inventory_items').length)).toBe(2);await expect(itemNames(page)).toHaveCount(240);expect(await page.evaluate(()=>(window as any).__inventory.requests.every((r:any)=>r.method==='GET'))).toBe(true);});
