import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';
import {expect,test,type Page} from '@playwright/test';
import {reactBrowserScripts} from './helpers/react-browser';

// Real ordinary Projects UI, query hook, SDK and synthetic persisted rows.
// Planner/financial/scheduling/provider/app seams are inert; only title/description and catalog controls execute.
const sourceRoot=process.env.BUBALY_PROJECTS_UI_SOURCE_ROOT||process.cwd();
const diagnostics=new WeakMap<Page,string[]>();
test.beforeEach(async({page})=>{const errors:string[]=[];diagnostics.set(page,errors);page.on('console',m=>{if(['warning','error'].includes(m.type()))errors.push(m.type()+': '+m.text());});page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url()));});
test.afterEach(async({page})=>{expect(diagnostics.get(page)).toEqual([]);expect(await page.evaluate(()=>(window as any).__projects.errors)).toEqual([]);});
const {react,reactDom}=reactBrowserScripts();
const icons=fs.readFileSync(path.join(path.dirname(require.resolve('lucide-react/package.json')),'dist/umd/lucide-react.min.js'),'utf8');
const sdk=fs.readFileSync(path.join(path.dirname(require.resolve('@supabase/supabase-js/package.json')),'dist/umd/supabase.js'),'utf8');
const isolated=new Set(['react','react-dom','lucide-react','next/navigation','next/link','@/components/app/app-context','@/components/i18n/locale-provider','@/components/i18n/use-format','@/components/ui/toast','@/lib/supabase/client','@/lib/offline/cache-scope','@/lib/projects/planner','@/lib/services/providers/compare','@/components/ai/ai-insight','@/components/ui/confirm']);
const modules:Record<string,{source:string;imports:Record<string,string>}>= {};
function collect(filename:string):string {
 const id=path.resolve([filename,filename+'.ts',filename+'.tsx',path.join(filename,'index.ts')].find(f=>fs.existsSync(f)&&fs.statSync(f).isFile())??filename);
 if(modules[id])return id;
 const raw=fs.readFileSync(id,'utf8');
 const source=/\.tsx?$/.test(id)?ts.transpileModule(raw,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React}}).outputText:raw;
 const item=modules[id]={source,imports:{} as Record<string,string>};
 for(const match of source.matchAll(/require\(["']([^"']+)["']\)/g)){const name=match[1];if(isolated.has(name)){item.imports[name]=name;continue;}item.imports[name]=collect(name.startsWith('@/')?path.join(sourceRoot,name.slice(2)):name.startsWith('.')?path.resolve(path.dirname(id),name):require.resolve(name,{paths:[path.dirname(id)]}));}
 return id;
}
const entry=collect(path.join(sourceRoot,'components/modules/projects-module.tsx'));
let css='';
test.beforeAll(async()=>{const config={exports:{} as any};const code=ts.transpileModule(fs.readFileSync(path.join(sourceRoot,'tailwind.config.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;new Function('module','exports','require',code)(config,config.exports,require);config.exports.default.content=[path.join(sourceRoot,'components/**/*.{ts,tsx}'),path.join(sourceRoot,'app/**/*.{ts,tsx}')];css=(await postcss([tailwindcss(config.exports.default),autoprefixer()]).process(fs.readFileSync(path.join(sourceRoot,'app/globals.css'),'utf8'),{from:path.join(sourceRoot,'app/globals.css')})).css;});
async function fixture(page:Page,seed=false,mode='success'){
 await page.route('**/*',async route=>{if(route.request().url()!=='https://projects-fixture.invalid/')throw Error('Unexpected native request '+route.request().url());await route.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body><main id="root"></main></body></html>'});});
 await page.goto('https://projects-fixture.invalid/');await page.addStyleTag({content:css});for(const content of [react,reactDom,'window.react=window.React;',icons,sdk])await page.addScriptTag({content});
 const messages=JSON.parse(fs.readFileSync(path.join(sourceRoot,'lib/i18n/messages/en-US.json'),'utf8'));
 await page.evaluate(({sources,entry,messages,seed,mode})=>{
  const w=window as any,R=w.React,D=w.ReactDOM;
  const row={id:'project-A',family_id:'family-A',created_by:'user-A',title:'Organize supplies',description:'Storage bins',kind:'repair',is_diy:true,priority:'medium',status:'idea',owner_id:'member-A',contractor_id:null,room:null,budget_cents:null,labor_cents:0,target_start:null,target_end:null,notes:null,updated_at:'fixture',created_at:'fixture'};
  const p=w.__projects={errors:[] as string[],notices:[] as any[],requests:[] as any[],store:seed?[row]:[],mode,readError:false,completedWrites:0,releases:[] as (()=>void)[],channels:[] as any[],context:{familyId:'family-A',userId:'user-A'},setContext:null as any,emit:()=>{for(const channel of p.channels)for(const callback of channel.callbacks)callback({eventType:'UPDATE',new:{},old:{}});}};
  window.addEventListener('error',e=>p.errors.push(e.message));window.addEventListener('unhandledrejection',e=>{p.errors.push(String(e.reason));e.preventDefault();});
  const fail=()=>{throw Error('Provider/money/AI/date workflow outside fixture');};
  const respond=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});
  const transport=async(input:any,options:any={})=>{
   const url=new URL(String(input));const table=url.pathname.split('/').pop();const method=options.method??'GET';
   if(url.origin!=='https://projects-store.invalid'||!['home_projects','project_materials','project_quotes','home_contractors'].includes(table??''))throw Error('Unexpected SDK request '+url);
   const patch=options.body?JSON.parse(String(options.body)):null;p.requests.push({table,method,query:url.search,patch});
   if(table!=='home_projects'){if(method!=='GET')fail();return respond([]);}
   if(method==='GET'){
    if(p.readError)return respond({code:'XX000',message:'Synthetic catalog readback unavailable'},500);
    let rows=p.store.filter((record:any)=>[...url.searchParams].every(([key,value])=>!value.startsWith('eq.')||String(record[key])===value.slice(3)));
    const order=url.searchParams.get('order');if(order){const keys=order.split(',');rows=[...rows].sort((a:any,b:any)=>{for(const item of keys){const [key,direction]=item.split('.');if(a[key]<b[key])return direction==='desc'?1:-1;if(a[key]>b[key])return direction==='desc'?-1:1;}return 0;});}
    const limit=url.searchParams.get('limit');if(limit)rows=rows.slice(0,Number(limit));return respond(rows);
   }
   if(!['POST','PATCH','DELETE'].includes(method))fail();
   if(p.mode==='hold')await new Promise<void>(resolve=>p.releases.push(resolve));
   p.completedWrites++;
   if(p.mode==='refusal')return respond({code:'XX000',message:'Synthetic save refused'},500);
   if(p.mode==='zero')return respond({code:'PGRST116',message:'No matching row',details:'The result contains 0 rows'},406);
   if(p.mode==='transport')throw new TypeError('Synthetic transport refusal');
   let changed:any;
   if(method==='POST'){changed={...row,id:'project-'+(p.store.length+1),...patch};p.store.push(changed);}
   else{changed=p.store.find((record:any)=>[...url.searchParams].every(([key,value])=>!value.startsWith('eq.')||String(record[key])===value.slice(3)));if(!changed)return respond({code:'PGRST116',message:'No matching row'},406);if(method==='DELETE')p.store=p.store.filter((record:any)=>record!==changed);else Object.assign(changed,patch);}
   if(p.mode==='readback-error')p.readError=true;
   const object=String(new Headers(options.headers).get('accept')).includes('vnd.pgrst.object');return respond(object?{id:changed.id}:[{id:changed.id}]);
  };
  const db=w.supabase.createClient('https://projects-store.invalid','synthetic-public-key',{global:{fetch:transport},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
  db.channel=()=>{const channel={callbacks:[] as any[],on(...args:any[]){this.callbacks.push(args.at(-1));return this;},subscribe(){return this;}};p.channels.push(channel);return channel;};db.removeChannel=async(channel:any)=>{p.channels=p.channels.filter((c:any)=>c!==channel);};
  const tr=(key:string,vars:Record<string,unknown>={})=>Object.entries(vars).reduce((s,[k,v])=>s.split('{'+k+'}').join(String(v)),messages[key]||key);
  const member={id:'member-A',user_id:'user-A',family_id:'family-A',display_name:'Alex',role:'parent'};
  const kinds=[{value:'repair',label:'Repair',emoji:'🔧'}],statuses=[{value:'idea',label:'Idea'},{value:'planning',label:'Planning'},{value:'in_progress',label:'In progress'},{value:'done',label:'Done'},{value:'cancelled',label:'Cancelled'}];
  const planner={PROJECT_KINDS:kinds,PROJECT_STATUSES:statuses,PRIORITIES:[{value:'medium',label:'Medium'},{value:'high',label:'High'},{value:'low',label:'Low'}],QUOTE_STATUSES:[],BOARD:[{key:'ideas',label:'Ideas',statuses:['idea']},{key:'planning',label:'Planning',statuses:['planning']},{key:'active',label:'Active',statuses:['in_progress']},{key:'done',label:'Done',statuses:['done','cancelled']}],kindMeta:()=>kinds[0],statusLabel:(s:string)=>statuses.find((item:any)=>item.value===s)?.label??s,columnFor:(s:string)=>s==='idea'?'ideas':s==='planning'?'planning':s==='in_progress'?'active':'done',suggestScope:()=>[],materialsTotals:()=>({count:0,purchased:0}),materialLineCents:fail,compareQuotes:()=>({received:0,awaiting:0}),budgetHealth:()=>({status:'no_budget',forecastCents:0,committedCents:0,remainingCents:0,pct:0}),schedule:()=>({state:'none'}),nextAction:()=> 'Review project',projectsSummary:()=>({overdue:0,over:0,text:'Ordinary projects fixture',active:0,ideas:0,forecastCents:0,budgetCents:0,dueSoon:0,quotesWaiting:0}),money:()=> '—',isoDate:fail};
  const mocks:Record<string,any>={react:R,'react-dom':D,'lucide-react':w.LucideReact,'next/navigation':{useRouter:()=>({push:fail,refresh:fail})},'next/link':{default:(props:any)=>R.createElement('a',props,props.children)},'@/components/app/app-context':{useApp:()=>({...p.context,role:'parent',members:[member],selfMember:member})},'@/components/i18n/locale-provider':{useTranslations:()=>tr,useLocale:()=>({code:'en-US'})},'@/components/i18n/use-format':{useFamilyClock:()=>({todayKey:fail}),useFormat:()=>({fmtDate:fail}),useFamilyCalendarToday:()=>null},'@/components/ui/toast':{useToast:()=>({success:(message:string)=>p.notices.push({kind:'success',message}),error:(message:string)=>p.notices.push({kind:'error',message})})},'@/lib/supabase/client':{createClient:()=>db},'@/lib/offline/cache-scope':{useAuthenticatedCacheScope:()=>null,isAuthenticatedCacheScopeCurrent:()=>true},'@/lib/projects/planner':planner,'@/lib/services/providers/compare':{compareQuotes:()=>({ranked:[],recommendation:null})},'@/components/ai/ai-insight':{AiInsight:()=>null},'@/components/ui/confirm':{useConfirm:()=>async()=>true}};
  const loaded:Record<string,any>={};function load(id:string):any{if(id in mocks)return mocks[id];if(loaded[id])return loaded[id].exports;const item=sources[id];if(!item)throw Error('Unexpected module '+id);const m=loaded[id]={exports:{}};new Function('require','module','exports',item.source)((name:string)=>load(item.imports[name]),m,m.exports);return m.exports;}
  function Host(){const [context,setContext]=R.useState(p.context);p.context=context;p.setContext=setContext;return R.createElement(load(entry).ProjectsModule);}
  const root=D.createRoot(document.getElementById('root'));root.render(R.createElement(Host));
 },{sources:modules,entry,messages,seed,mode});
 await expect(page.getByRole('heading',{name:'Home Projects',exact:true})).toBeVisible();
 if(seed)await expect(page.getByText('Organize supplies',{exact:true})).toBeVisible();else await expect(page.getByText('No projects yet',{exact:true})).toBeVisible();
}
async function draft(page:Page,title='Organize supplies',description='Storage bins'){await page.getByRole('button',{name:'New project',exact:true}).click();const d=page.getByRole('dialog');await expect(d).toHaveCount(1);await d.locator('input[name=title]').fill(title);await d.locator('textarea[name=description]').fill(description);}
async function save(page:Page){await page.getByRole('dialog').filter({has:page.locator('input[name=title]')}).getByRole('button',{name:'Save project',exact:true}).click();}
async function notices(page:Page){return page.evaluate(()=>(window as any).__projects.notices);}
async function wrote(page:Page){return page.evaluate(()=>(window as any).__projects.requests.filter((r:any)=>r.method!=='GET'));}
test('confirmed creation updates the catalog without requiring a realtime event',async({page})=>{await fixture(page);await draft(page,'  Organize supplies  ','  Storage bins  ');await save(page);await expect.poll(()=>page.evaluate(()=>(window as any).__projects.store.length)).toBe(1);expect(await page.evaluate(()=>(window as any).__projects.store[0])).toMatchObject({title:'Organize supplies',description:'Storage bins'});await expect(page.getByText('Organize supplies',{exact:true}).first()).toBeVisible();});
test('confirmed title edit refreshes the open detail and catalog',async({page})=>{await fixture(page,true);await page.getByText('Organize supplies',{exact:true}).click();await page.getByRole('button',{name:'Edit project',exact:true}).click();await page.locator('input[name=title]').fill('Sort supplies');await page.locator('textarea[name=description]').fill('Labeled bins');await save(page);expect(await page.evaluate(()=>(window as any).__projects.store[0].title)).toBe('Sort supplies');await expect(page.getByRole('heading',{name:/Sort supplies/})).toBeVisible();});
test('confirmed removal refreshes the empty catalog without a realtime event',async({page})=>{await fixture(page,true);await page.getByText('Organize supplies',{exact:true}).click();await page.getByRole('button',{name:'Delete project',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__projects.store.length)).toBe(0);await expect(page.getByText('No projects yet',{exact:true})).toBeVisible();});
test('completion of a closed editor preserves a newer project draft',async({page})=>{await fixture(page,false,'hold');await draft(page,'Older project','Older draft');await save(page);await expect.poll(()=>page.evaluate(()=>(window as any).__projects.releases.length)).toBe(1);await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await draft(page,'Newer project','Keep this draft');await page.evaluate(()=>{const p=(window as any).__projects;p.mode='success';p.releases.splice(0).forEach((release:any)=>release());});await expect.poll(()=>page.evaluate(()=>(window as any).__projects.store.length)).toBe(1);await expect(page.locator('input[name=title]')).toHaveValue('Newer project');await expect(page.locator('textarea[name=description]')).toHaveValue('Keep this draft');});
for(const mode of ['refusal','zero','transport'])test(mode+' preserves the project draft without success feedback',async({page})=>{await fixture(page,false,mode);await draft(page);await save(page);await expect.poll(()=>page.evaluate(()=>(window as any).__projects.notices.filter((n:any)=>n.kind==='error').length)).toBe(1);await expect(page.locator('input[name=title]')).toHaveValue('Organize supplies');await expect(page.locator('textarea[name=description]')).toHaveValue('Storage bins');await expect(page.getByRole('button',{name:'Save project',exact:true})).toBeEnabled();expect(await page.evaluate(()=>(window as any).__projects.store)).toEqual([]);expect((await notices(page)).some((n:any)=>n.kind==='success')).toBe(false);expect(await wrote(page)).toHaveLength(1);});
test('a delivered realtime event renders the same confirmed synthetic store row',async({page})=>{await fixture(page);await draft(page);await save(page);await expect.poll(()=>page.evaluate(()=>(window as any).__projects.store.length)).toBe(1);await page.evaluate(()=>(window as any).__projects.emit());await expect(page.getByText('Organize supplies',{exact:true}).first()).toBeVisible();await expect(page.getByRole('heading',{name:/Organize supplies/})).toBeVisible();expect(await wrote(page)).toHaveLength(1);});
test('old confirmed creation refreshes the catalog without opening detail or reporting stale success',async({page})=>{await fixture(page,false,'hold');await draft(page,'Older project');await save(page);await expect.poll(()=>page.evaluate(()=>(window as any).__projects.releases.length)).toBe(1);await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await page.evaluate(()=>{const p=(window as any).__projects;p.mode='success';p.releases.splice(0).forEach((release:any)=>release());});await expect(page.getByText('Older project',{exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);expect(await notices(page)).toEqual([]);expect(await wrote(page)).toHaveLength(1);});
for(const mode of ['refusal','transport'])test('old '+mode+' cannot overwrite feedback or loading for a newer draft',async({page})=>{await fixture(page,false,'hold');await draft(page,'Older project');await save(page);await expect.poll(()=>page.evaluate(()=>(window as any).__projects.releases.length)).toBe(1);await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await draft(page,'Newer project','Keep this draft');await page.evaluate(mode=>{const p=(window as any).__projects;p.mode=mode;p.releases.splice(0).forEach((release:any)=>release());},mode);await expect.poll(()=>page.evaluate(()=>(window as any).__projects.completedWrites)).toBe(1);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await expect(page.locator('input[name=title]')).toHaveValue('Newer project');await expect(page.getByRole('button',{name:'Save project',exact:true})).toBeEnabled();expect(await notices(page)).toEqual([]);});
test('the newer draft can save after the older confirmed completion',async({page})=>{await fixture(page,false,'hold');await draft(page,'Older project');await save(page);await expect.poll(()=>page.evaluate(()=>(window as any).__projects.releases.length)).toBe(1);await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await draft(page,'Newer project','Current description');await page.evaluate(()=>{const p=(window as any).__projects;p.mode='success';p.releases.splice(0).forEach((release:any)=>release());});await expect(page.getByText('Older project',{exact:true})).toBeVisible();await save(page);await expect(page.getByRole('heading',{name:/Newer project/})).toBeVisible();expect(await page.evaluate(()=>(window as any).__projects.store.map((r:any)=>r.title))).toEqual(['Older project','Newer project']);expect((await notices(page)).filter((n:any)=>n.kind==='success')).toHaveLength(1);expect(await wrote(page)).toHaveLength(2);});
test('confirmed creation with failed readback shows recovery without a false success or duplicate draft',async({page})=>{await fixture(page,false,'readback-error');await draft(page);await save(page);await expect(page.getByText('Could not load your projects. Refresh and try again.',{exact:true})).toBeVisible();await expect(page.locator('input[name=title]')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__projects.store.length)).toBe(1);expect((await notices(page)).some((n:any)=>n.kind==='success')).toBe(false);expect(await wrote(page)).toHaveLength(1);await page.evaluate(()=>{const p=(window as any).__projects;p.readError=false;p.mode='success';});await page.getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByText('Organize supplies',{exact:true}).first()).toBeVisible();expect(await wrote(page)).toHaveLength(1);});
test('a changed ordinary context retires an older held editor completion',async({page})=>{await fixture(page,false,'hold');await draft(page,'Older project');await save(page);await expect.poll(()=>page.evaluate(()=>(window as any).__projects.releases.length)).toBe(1);await page.evaluate(()=>(window as any).__projects.setContext({familyId:'family-B',userId:'user-B'}));await expect(page.locator('input[name=title]')).toHaveCount(0);await expect(page.getByText('No projects yet',{exact:true})).toBeVisible();await page.evaluate(()=>{const p=(window as any).__projects;p.mode='success';p.releases.splice(0).forEach((release:any)=>release());});await expect.poll(()=>page.evaluate(()=>(window as any).__projects.store.length)).toBe(1);await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByText('No projects yet',{exact:true})).toBeVisible();expect(await notices(page)).toEqual([]);expect(await wrote(page)).toHaveLength(1);});
