import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import {test,expect,type Page} from '@playwright/test';
import {reactBrowserScripts} from './helpers/react-browser';

// Actual hook/React19/installed SDK. All app auth/session/cache/realtime seams inert.
const root=process.env.BUBALY_QUERY_SHAPE_SOURCE_ROOT ?? process.cwd();
const {react,reactDom}=reactBrowserScripts();
const sdkPath=path.join(path.dirname(require.resolve('@supabase/supabase-js/package.json')),'dist/umd/supabase.js');
const sdk=fs.readFileSync(sdkPath,'utf8');
const sources=Object.fromEntries(['lib/hooks/use-realtime-query.ts','lib/supabase/errors.ts','lib/realtime/own-channel.ts'].map(file=>['@/'+file.replace(/\.ts$/,''),ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText]));
const errors=new WeakMap<Page,string[]>();
test.beforeEach(({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type()))list.push(m.type()+': '+m.text());});page.on('requestfailed',r=>list.push(r.url()));});
test.afterEach(async({page})=>{
 const receipt=await page.evaluate(()=>{const p=(window as any).__queryShape;return {requests:p.requests,replies:p.replies,settled:p.settled,renders:p.renders,confirmations:p.confirmations,cacheWrites:p.cacheWrites,cacheReads:p.cacheReads,forbidden:p.forbidden,transportErrors:p.transportErrors};});
 await test.info().attach('finite actual SDK query receipt',{body:JSON.stringify(receipt),contentType:'application/json'});
 expect(receipt.forbidden).toEqual([]);expect(receipt.transportErrors).toEqual([]);expect(receipt.requests.length).toBeLessThanOrEqual(5);expect(receipt.settled).toBe(receipt.requests.length);expect(errors.get(page)).toEqual([]);
});
async function fixture(page:Page,cache=false,seed?:unknown[]){
 await page.route('**/*',async route=>{if(route.request().url()!=='https://query-shape-fixture.invalid/')throw Error('Unexpected browser transport '+route.request().url());await route.fulfill({contentType:'text/html',body:'<!doctype html><html><body><main id="root"></main></body></html>'});});
 await page.goto('https://query-shape-fixture.invalid/');for(const content of[react,reactDom,sdk])await page.addScriptTag({content});
 await page.evaluate(({sources,cache,seed})=>{
  const w=window as any,R=w.React,D=w.ReactDOM,p:any=w.__queryShape={requests:[],replies:[],settled:0,renders:[],confirmations:[],cacheWrites:[],cacheReads:[],forbidden:[],transportErrors:[],releases:[],family:'family-A',cache,seeds:new Map(),scopes:new Map(),dataError:new Map(),undefinedData:new Set()};
  const deny=(label:string)=>{p.forbidden.push(label);throw Error('Outside ordinary query shape fixture: '+label);};
  if(seed)p.seeds.set('inventory_moves:family-A',{rows:seed,savedAt:123});
  const transport=async(input:any,init:any={})=>{try{
   const u=new URL(String(input)),method=init.method??'GET';
   if(u.origin!=='https://query-shape-store.invalid'||u.pathname!=='/rest/v1/inventory_moves'||method!=='GET'||!['eq.family-A','eq.family-B'].includes(u.searchParams.get('family_id')??'')||u.searchParams.get('select')!=='id,family_id,name')deny('unexpected SDK read');
   if(p.requests.length>=5)deny('finite GET request bound');
   const index=p.requests.length;p.requests.push({index,method,path:u.pathname,query:u.search,family:u.searchParams.get('family_id')});
   const response:any=await new Promise(resolve=>{p.releases[index]=resolve;});p.settled++;
   return new Response(JSON.stringify(response.body),{status:response.status,headers:{'content-type':'application/json'}});
  }catch(error){p.transportErrors.push(error instanceof Error?error.message:String(error));throw error;}};
  // Null accessToken callback bypasses SDK Auth client/session lookup entirely.
  const db=w.supabase.createClient('https://query-shape-store.invalid','synthetic-public-key',{accessToken:async()=>null,global:{fetch:transport},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
  db.channel=()=>deny('realtime subscription');db.removeChannel=()=>deny('realtime removal');
  const scopeFor=(family:string)=>{if(!p.scopes.has(family))p.scopes.set(family,{key:'synthetic-scope:'+family,partition:'inert-partition:'+family,familyId:family,error:'Synthetic context inactive',familyMismatchError:'Synthetic family mismatch'});return p.scopes.get(family);};
  const mocks:Record<string,any>={react:R,'@/lib/supabase/client':{createClient:()=>db},'@/lib/offline/cache-scope':{useAuthenticatedCacheScope:()=>p.cache?scopeFor(p.family):null,isAuthenticatedCacheScopeCurrent:()=>true},'@/lib/offline/cache':{cacheKey:(table:string,family:string)=>table+':'+family,getCacheGeneration:()=>0,subscribeCacheInvalidation:()=>()=>{},cacheIdentity:(_partition:any,table:string,family:string)=>({key:table+':'+family,signature:'inert-signature:'+family}),readPartitionedCache:(identity:any)=>{p.cacheReads.push(identity);return p.seeds.get(identity.key)??null;},writePartitionedCache:(identity:any,rows:any)=>{p.cacheWrites.push({identity,rows:JSON.parse(JSON.stringify(rows))});}},'@/lib/realtime/published-tables':{realtimeChannelFor:()=>null}};
  const loaded:Record<string,any>={};function load(id:string):any{if(id in mocks)return mocks[id];if(loaded[id])return loaded[id].exports;const source=sources[id as keyof typeof sources];if(!source)deny('unapproved application import '+id);const entry=loaded[id]={exports:{}};new Function('require','module','exports',source)(load,entry,entry.exports);return entry.exports;}
  const {useRealtimeQuery}=load('@/lib/hooks/use-realtime-query');
  function Consumer({family}:{family:string}){
   const query=useRealtimeQuery({table:'inventory_moves',familyId:family,fetcher:async(sb:any)=>{const reply=await sb.from('inventory_moves').select('id,family_id,name').eq('family_id',family);const index=p.replies.length;p.replies.push({data:reply.data,error:reply.error});if(p.undefinedData.has(index))return {data:undefined,error:null};return p.dataError.has(index)?{data:reply.data,error:{message:p.dataError.get(index)}}:reply;}});
   p.state=query;p.confirm=async()=>{const result=await query.refreshAndConfirm();p.confirmations.push({result,committed:p.snapshot()});};
   const snapshot={family,data:query.data,loading:query.loading,error:query.error,stale:query.stale,updatedAt:query.updatedAt};p.renders.push(snapshot);
   return R.createElement('pre',{id:'snapshot'},JSON.stringify(snapshot));
  }
  let renderRoot:any;p.mount=(family='family-A')=>{p.family=family;renderRoot??=D.createRoot(document.getElementById('root'));D.flushSync(()=>renderRoot.render(R.createElement(Consumer,{family})));};
  p.unmount=()=>{D.flushSync(()=>renderRoot.unmount());renderRoot=null;};
  p.snapshot=()=>{const el=document.getElementById('snapshot');return el?JSON.parse(el.textContent??'null'):null;};
  p.flush=()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
  p.settle=(index:number,body:any,status=200,error?:string)=>{if(error)p.dataError.set(index,error);p.releases[index]({body,status});};
  p.mount();
 },{sources,cache,seed});
 await count(page,1);await flush(page);
}
async function count(page:Page,n:number){await expect.poll(()=>page.evaluate(()=>(window as any).__queryShape.requests.length)).toBe(n);}
async function flush(page:Page){await page.evaluate(()=>(window as any).__queryShape.flush());}
async function snapshot(page:Page){return page.evaluate(()=>(window as any).__queryShape.snapshot());}
async function settle(page:Page,index:number,body:unknown,status=200,error?:string){await page.evaluate(({index,body,status,error})=>(window as any).__queryShape.settle(index,body,status,error),{index,body,status,error});await flush(page);}
async function confirm(page:Page,n:number){await page.evaluate(()=>{void (window as any).__queryShape.confirm();});await count(page,n);}
const A=[{id:'ordinary-A',family_id:'family-A',name:'Synthetic A'}],B=[{id:'ordinary-B',family_id:'family-B',name:'Synthetic B'}];
async function refused(page:Page,rows:unknown[]){expect.soft(await snapshot(page)).toMatchObject({data:rows,loading:false,stale:true,error:expect.any(String)});expect.soft((await snapshot(page)).error).not.toBeNull();}

for(const body of[{length:1,0:A[0]},'X'])test('network-only SDK200 '+(typeof body==='string'?'string':'indexed object')+' refuses malformed collection rather than fresh usable data',async({page})=>{await fixture(page);await settle(page,0,body);await refused(page,[]);expect.soft((await snapshot(page)).updatedAt).toBeNull();expect(await page.evaluate(()=>(window as any).__queryShape.cacheWrites)).toEqual([]);});
test('malformed latest object retains previous network rows and refuses waiter confirmation',async({page})=>{await fixture(page);await settle(page,0,A);const at=(await snapshot(page)).updatedAt;await confirm(page,2);await settle(page,1,{length:1,0:A[0]});await refused(page,A);expect.soft((await snapshot(page)).updatedAt).toBe(at);expect.soft(await page.evaluate(()=>(window as any).__queryShape.confirmations)).toEqual([{result:{ok:false,reason:'error',error:expect.any(String)},committed:expect.objectContaining({data:A,stale:true,error:expect.any(String)})}]);});
test('malformed latest string never reaches inert cache write observer or successful confirmation',async({page})=>{await fixture(page,true);await settle(page,0,A);await confirm(page,2);await settle(page,1,'X');await refused(page,A);expect.soft(await page.evaluate(()=>(window as any).__queryShape.cacheWrites.map((w:any)=>w.rows))).toEqual([A]);expect.soft(await page.evaluate(()=>(window as any).__queryShape.confirmations[0])).toMatchObject({result:{ok:false,reason:'error'},committed:{data:A,stale:true}});});
test('healthy SDK array is fresh, observed as array and confirmed after commit',async({page})=>{await fixture(page,true);await settle(page,0,A);await confirm(page,2);await settle(page,1,A);expect(await snapshot(page)).toMatchObject({data:A,loading:false,error:null,stale:false});expect((await snapshot(page)).updatedAt).toBeGreaterThan(0);expect(await page.evaluate(()=>(window as any).__queryShape.cacheWrites.map((w:any)=>w.rows))).toEqual([A,A]);expect(await page.evaluate(()=>(window as any).__queryShape.confirmations[0])).toMatchObject({result:{ok:true},committed:{data:A,error:null,stale:false}});});
test('healthy SDK empty array remains complete empty',async({page})=>{await fixture(page);await settle(page,0,[]);expect(await snapshot(page)).toMatchObject({data:[],loading:false,error:null,stale:false});});
test('current null success retains intentional empty-array contract',async({page})=>{await fixture(page,true);await settle(page,0,null);expect(await snapshot(page)).toMatchObject({data:[],loading:false,error:null,stale:false});expect(await page.evaluate(()=>(window as any).__queryShape.cacheWrites.map((w:any)=>w.rows))).toEqual([[]]);});
test('explicit SDK403 refuses and retains prior array without new cache observation',async({page})=>{await fixture(page,true);await settle(page,0,A);await confirm(page,2);await settle(page,1,{code:'42501',message:'Synthetic read refused'},403);await refused(page,A);expect(await page.evaluate(()=>(window as any).__queryShape.cacheWrites.map((w:any)=>w.rows))).toEqual([A]);expect(await page.evaluate(()=>(window as any).__queryShape.confirmations[0].result)).toMatchObject({ok:false,reason:'error'});});
test('explicit data plus error adapter refuses even when actual SDK delivered a healthy array',async({page})=>{await fixture(page,true);await settle(page,0,A);await confirm(page,2);await settle(page,1,A,200,'Synthetic explicit fetcher error');await refused(page,A);expect(await page.evaluate(()=>(window as any).__queryShape.replies[1])).toEqual({data:A,error:null});expect(await page.evaluate(()=>(window as any).__queryShape.cacheWrites.map((w:any)=>w.rows))).toEqual([A]);expect(await page.evaluate(()=>(window as any).__queryShape.confirmations[0].result)).toEqual({ok:false,reason:'error',error:'Synthetic explicit fetcher error'});});
test('family retirement rejects waiter while late malformed A cannot disturb healthy B',async({page})=>{await fixture(page,true);await settle(page,0,A);await confirm(page,2);await page.evaluate(()=>(window as any).__queryShape.mount('family-B'));await count(page,3);await flush(page);expect(await page.evaluate(()=>(window as any).__queryShape.confirmations[0].result)).toEqual({ok:false,reason:'inactive'});await settle(page,2,B);await settle(page,1,{length:1});expect(await snapshot(page)).toMatchObject({family:'family-B',data:B,error:null,stale:false});expect(await page.evaluate(()=>(window as any).__queryShape.cacheWrites.map((w:any)=>w.rows))).toEqual([A,B]);});
test('family A B A gives latest A a new lifetime and ignores both obsolete bodies',async({page})=>{await fixture(page);await page.evaluate(()=>(window as any).__queryShape.mount('family-B'));await count(page,2);await page.evaluate(()=>(window as any).__queryShape.mount('family-A'));await count(page,3);await settle(page,2,A);await settle(page,0,'X');await settle(page,1,{length:1});expect(await snapshot(page)).toMatchObject({family:'family-A',data:A,error:null,stale:false});});
test('latest overlapping healthy request inherits waiter and ignores old malformed body',async({page})=>{await fixture(page,true);await settle(page,0,A);await confirm(page,2);await page.evaluate(()=>{void (window as any).__queryShape.state.refresh();});await count(page,3);await settle(page,1,'X');expect(await page.evaluate(()=>(window as any).__queryShape.confirmations)).toEqual([]);await settle(page,2,A);expect(await page.evaluate(()=>(window as any).__queryShape.confirmations[0])).toMatchObject({result:{ok:true},committed:{data:A,error:null,stale:false}});expect(await page.evaluate(()=>(window as any).__queryShape.cacheWrites.map((w:any)=>w.rows))).toEqual([A,A]);});
test('latest overlapping error refuses waiter despite older healthy response',async({page})=>{await fixture(page);await settle(page,0,A);await confirm(page,2);await page.evaluate(()=>{void (window as any).__queryShape.state.refresh();});await count(page,3);await settle(page,1,A);await settle(page,2,{message:'Synthetic newest unavailable'},500);await refused(page,A);expect(await page.evaluate(()=>(window as any).__queryShape.confirmations[0].result)).toMatchObject({ok:false,reason:'error'});});
test('local setData retires waiter and late malformed read cannot overwrite local stale array',async({page})=>{await fixture(page);await settle(page,0,A);await confirm(page,2);await page.evaluate(()=>(window as any).__queryShape.state.setData([{id:'local'}]));await flush(page);await settle(page,1,'X');expect(await snapshot(page)).toMatchObject({data:[{id:'local'}],stale:true,error:null});expect(await page.evaluate(()=>(window as any).__queryShape.confirmations[0].result)).toEqual({ok:false,reason:'superseded'});});
test('unmount retires waiter and late malformed receipt has no cache observer side effect',async({page})=>{await fixture(page,true);await settle(page,0,A);await confirm(page,2);await page.evaluate(()=>(window as any).__queryShape.unmount());await settle(page,1,'X');expect(await snapshot(page)).toBeNull();expect(await page.evaluate(()=>(window as any).__queryShape.confirmations[0].result)).toEqual({ok:false,reason:'inactive'});expect(await page.evaluate(()=>(window as any).__queryShape.cacheWrites.map((w:any)=>w.rows))).toEqual([A]);});
test('inert seeded cache array remains stale until healthy actual SDK array commits',async({page})=>{await fixture(page,true,A);expect(await snapshot(page)).toMatchObject({data:A,stale:true,updatedAt:123});await settle(page,0,A);expect(await snapshot(page)).toMatchObject({data:A,loading:false,stale:false,error:null});expect(await page.evaluate(()=>(window as any).__queryShape.cacheReads)).toHaveLength(1);});

// All sixteen original complete case declarations/assertions above retained.
test('malformed newest read refuses inherited waiter despite earlier healthy completion',async({page})=>{await fixture(page,true);await settle(page,0,A);await confirm(page,2);await page.evaluate(()=>{void (window as any).__queryShape.state.refresh();});await count(page,3);await settle(page,1,A);expect(await page.evaluate(()=>(window as any).__queryShape.confirmations)).toEqual([]);await settle(page,2,'X');await refused(page,A);expect.soft(await page.evaluate(()=>(window as any).__queryShape.confirmations[0])).toMatchObject({result:{ok:false,reason:'error'},committed:{data:A,stale:true}});expect.soft(await page.evaluate(()=>(window as any).__queryShape.cacheWrites.map((w:any)=>w.rows))).toEqual([A]);});
test('undefined-data legacy adapter keeps nullish empty semantics after actual SDK healthy array',async({page})=>{await fixture(page,true);await page.evaluate(()=>(window as any).__queryShape.undefinedData.add(0));await settle(page,0,[]);expect(await snapshot(page)).toMatchObject({data:[],loading:false,error:null,stale:false});expect(await page.evaluate(()=>(window as any).__queryShape.replies[0])).toEqual({data:[],error:null});expect(await page.evaluate(()=>(window as any).__queryShape.cacheWrites.map((w:any)=>w.rows))).toEqual([[]]);});
test('raw SDK array entries remain unchanged without imposing row schema policy',async({page})=>{const rows=[null,7,'ordinary opaque entry'];await fixture(page,true);await settle(page,0,rows);expect(await snapshot(page)).toMatchObject({data:rows,loading:false,error:null,stale:false});expect(await page.evaluate(()=>(window as any).__queryShape.cacheWrites.map((w:any)=>w.rows))).toEqual([rows]);});

for(const body of[{},42,false])test('non-nullish SDK200 '+(typeof body==='object'?'plain object':typeof body)+' refuses malformed collection',async({page})=>{await fixture(page);await settle(page,0,body);await refused(page,[]);expect.soft((await snapshot(page)).updatedAt).toBeNull();expect(await page.evaluate(()=>(window as any).__queryShape.replies[0])).toEqual({data:body,error:null});});
test('current malformed read can recover with a healthy retry and committed confirmation',async({page})=>{await fixture(page,true);await settle(page,0,A);const at=(await snapshot(page)).updatedAt;await confirm(page,2);await settle(page,1,'X');await refused(page,A);expect.soft((await snapshot(page)).updatedAt).toBe(at);expect.soft(await page.evaluate(()=>(window as any).__queryShape.confirmations[0].result)).toMatchObject({ok:false,reason:'error'});const next=[{...A[0],name:'Synthetic retry'}];await confirm(page,3);await settle(page,2,next);expect(await snapshot(page)).toMatchObject({data:next,error:null,stale:false,loading:false});expect.soft(await page.evaluate(()=>(window as any).__queryShape.cacheWrites.map((w:any)=>w.rows))).toEqual([A,next]);expect(await page.evaluate(()=>(window as any).__queryShape.confirmations[1])).toMatchObject({result:{ok:true},committed:{data:next,error:null,stale:false}});});
