import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const nativeRequire=createRequire(import.meta.url);
import ts from 'typescript';
import { createClient } from '@supabase/supabase-js';
import { afterAll, afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
const sourceRoot=process.env.BUBALY_CALENDAR_UPDATE_SOURCE_ROOT??process.cwd();
const paths={calendar:'lib/services/calendar/index.ts',idempotency:'lib/services/idempotency.ts',types:'lib/services/types.ts',errors:'lib/supabase/errors.ts',eventDates:'lib/calendar/event-dates.ts',calendarWindow:'lib/briefing/calendar-window.ts',occurrences:'lib/calendar/occurrences.ts',recurrence:'lib/calendar/recurrence.ts',zoned:'lib/time/zoned.ts', calendarDay: 'lib/calendar/day.ts', sourceCapability: 'lib/calendar/source-capability.ts'};
const sources=Object.fromEntries(Object.entries(paths).filter(([name]) => name !== 'sourceCapability').map(([name,file])=>[name,ts.transpileModule(fs.readFileSync(path.join(sourceRoot,file),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText]));
// Historical source roots may predate this import. Read the exact real module
// only when their occurrences reader requests it; a missing requested file
// remains a hard ENOENT failure, never a fabricated or disabled capability.
function sourceFor(name: string): string {
  if (name === 'sourceCapability') return ts.transpileModule(fs.readFileSync(path.join(sourceRoot, paths.sourceCapability), 'utf8'), { compilerOptions: { target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS } }).outputText;
  if (!Object.hasOwn(sources, name)) throw new Error('Unknown finite source ' + name);
  return sources[name];
}

const A='aaaaaaaa-aaaa-4aaa-8aaa-000000000001',B='bbbbbbbb-bbbb-4bbb-8bbb-000000000001',ownA='aaaaaaaa-aaaa-4aaa-8aaa-000000000002',ownB='bbbbbbbb-bbbb-4bbb-8bbb-000000000002',eventId='cccccccc-cccc-4ccc-8ccc-000000000001',userId='dddddddd-dddd-4ddd-8ddd-000000000001';
const traces:any[]=[];let trace:any;
beforeEach(()=>{trace={name:expect.getState().currentTestName,requests:[],transportErrors:[],forbidden:[],settled:0,activity:[],logs:[]};for(const method of ['error','warn'] as const)vi.spyOn(console,method).mockImplementation((...args)=>trace.logs.push({method,args}));});
afterEach(()=>{traces.push(trace);expect(trace.forbidden).toEqual([]);expect(trace.transportErrors).toEqual([]);expect(trace.requests.length).toBeLessThanOrEqual(2);expect(trace.settled).toBe(trace.requests.length);for(const r of trace.requests){if(r.table==='calendar_events'){expect(r.method).toBe('PATCH');expect(r.query).toEqual({id:'eq.'+trace.targetId,family_id:'eq.'+trace.family,feed_id:'is.null',external_uid:'is.null',select:'*'});expect(r.accept).toBeNull();expect(r.prefer).toBe('return=representation');}else{expect(r.table).toBe('family_members');expect(r.method).toBe('GET');expect(r.query).toEqual({select:'id,family_id',family_id:'eq.'+trace.family,id:'eq.'+trace.requestedAssignee});}}expect(trace.logs.every((l:any)=>String(l.args[0]).startsWith('[service:calendar] update failed'))).toBe(true);vi.restoreAllMocks();});
afterAll(()=>{if(process.env.BUBALY_CALENDAR_UPDATE_TRACE)fs.writeFileSync(process.env.BUBALY_CALENDAR_UPDATE_TRACE,JSON.stringify(traces,null,2)+'\n',{flag:'wx'});});
type Options={family?:string;patch?:Record<string,unknown>;targetId?:string;targetMissing?:boolean;targetForeign?:boolean;writeStatus?:403|500;dataError?:boolean;memberBody?:unknown;memberStatus?:403;memberDataError?:boolean;patchArray?:boolean;patchEmpty?:boolean};
function fixture(options:Options={}){
 const family=options.family??A,own=family.toLowerCase()===A?ownA:ownB,patch=options.patch??{assigneeId:own},targetId=options.targetId??eventId;
 trace.family=family;trace.targetId=targetId;trace.requestedAssignee=patch.assigneeId;
 const saved={id:eventId,family_id:family.toLowerCase(),title:'Neutral event',starts_at:'2026-01-02T10:00:00.000Z',ends_at:'2026-01-02T11:00:00.000Z',all_day:false,location:'Neutral room',description:null,category:'general',recurrence:'none',recurrence_until:null,assignee_id:own,created_by:userId};
 const deny=(reason:string):never=>{trace.forbidden.push(reason);throw new Error(reason);};
 const transport:typeof fetch=async(resource,init)=>{try{const url=new URL(String(resource)),method=init?.method??'GET',table=url.pathname.split('/').at(-1)!;if(url.origin!=='https://calendar-update.invalid'||!['family_members','calendar_events'].includes(table)||trace.requests.length>=2)deny('Outside finite Calendar update proof');const query=Object.fromEntries(url.searchParams),payload=init?.body?JSON.parse(String(init.body)):undefined,headers=new Headers(init?.headers);trace.requests.push({method,table,query,payload,accept:headers.get('accept'),prefer:headers.get('prefer')});
 if(table==='family_members'){if(method!=='GET'||query.family_id!=='eq.'+family||query.id!=='eq.'+patch.assigneeId||query.select!=='id,family_id')deny('Unscoped requested member lookup');const body=Object.hasOwn(options,'memberBody')?options.memberBody:(typeof patch.assigneeId==='string'&&patch.assigneeId.toLowerCase()===own?[{id:own,family_id:family.toLowerCase()}]:[]);return new Response(JSON.stringify(options.memberStatus?{code:'42501',message:'Synthetic member read denied'}:body),{status:options.memberStatus??200,headers:{'content-type':'application/json'}});}
 if(method!=='PATCH'||query.id!=='eq.'+targetId||query.family_id!=='eq.'+family||query.feed_id!=='is.null'||query.external_uid!=='is.null'||query.select!=='*')deny('Unscoped event update');if('family_id'in payload||'id'in payload)deny('Unexpected scope mutation in patch');
 const status=options.writeStatus??200;const row=options.targetMissing||options.targetForeign?null:{...saved,...payload,assignee_id:typeof payload.assignee_id==='string'?payload.assignee_id.toLowerCase():('assignee_id'in payload?payload.assignee_id:saved.assignee_id)};trace.lastRow=row;
 return new Response(JSON.stringify(status!==200?{code:status===403?'42501':'XX000',message:'Synthetic event update refused'}:(options.patchEmpty?[]:options.patchArray?[row]:row)),{status,headers:{'content-type':'application/json'}});
 }catch(error){trace.transportErrors.push(String(error));throw error;}finally{trace.settled++;}};
 const sdk=createClient('https://calendar-update.invalid','synthetic-key',{accessToken:async()=>null,auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},global:{fetch:transport}});let db:any=sdk;
 if(options.dataError||options.memberDataError){db={from:(table:string)=>{if((table!=='calendar_events'||!options.dataError)&&(table!=='family_members'||!options.memberDataError))return sdk.from(table);let current:any=sdk.from(table);const proxy:any=new Proxy({},{get(_target,key){if(key==='then')return(resolve:any,reject:any)=>current.then((reply:any)=>{trace.adapter=table==='calendar_events'?'Actual healthy PATCH receipt → explicit data+error precedence adapter':'Actual healthy member receipt → explicit data+error precedence adapter';resolve({...reply,error:{code:'42501',message:'Synthetic read or update denial with data'}});},reject);const value=Reflect.get(current,key,current);return typeof value==='function'?(...args:any[])=>{const result=value.apply(current,args);if(result&&typeof result==='object')current=result;return proxy;}:value;}});return proxy;}};}
 const scope:any={db,familyId:family,userId,memberId:own,role:'parent',actorKind:'member',tz:'UTC',now:new Date('2026-01-01T00:00:00Z')},loaded:any={};const unused=(name:string)=>new Proxy({},{get:()=>()=>deny('Unused seam '+name)});
 function load(name:string):any{if(loaded[name])return loaded[name];const entry={exports:{}};loaded[name]=entry.exports;const require=(id:string):any=>{const dependency:Record<string,string>={'@/lib/calendar/event-dates':'eventDates','@/lib/briefing/calendar-window':'calendarWindow','@/lib/calendar/occurrences':'occurrences','@/lib/calendar/recurrence':'recurrence','@/lib/time/zoned':'zoned', '@/lib/calendar/day': 'calendarDay', './source-capability': 'sourceCapability'};if(dependency[id])return load(dependency[id]);if (id === '@/lib/calendar/source-capability') return { CALENDAR_SOURCE_ARCHIVE_ENABLED: false };
    if (id === '@/lib/calendar/display-spans') return { calendarDisplayDay: () => deny('Unused read seam calendarDisplayDay') };
    if (id === '@/lib/onboarding/ics-time') return { validDay: () => deny('Unused read seam validDay') };
    if(id==='server-only')return{};if(id==='../types'||id==='./types')return load('types');if(id==='node:crypto')return nativeRequire(id);if(id==='../idempotency')return new Proxy({},{get:(_target,key)=>key==='sameId'?load('idempotency').sameId:()=>deny('Unused idempotency export '+String(key))});if(id==='@/lib/supabase/errors')return load('errors');if(id==='../activity')return{recordActivitySafely:async(actualScope:any,descriptor:any)=>{if(actualScope!==scope)deny('Activity observer received another scope');trace.activity.push(descriptor);}};if(['../idempotency','../scope','@/lib/i18n/server','@/lib/home/conflicts','@/lib/calendar/scheduling','@/lib/supabase/settle','@/lib/supabase/escape-like'].includes(id))return unused(id);return deny('Forbidden import '+id);};new Function('require','module','exports',sourceFor(name))(require,entry,entry.exports);loaded[name]=entry.exports;return entry.exports;}
 return{run:()=>load('calendar').updateEvent(scope,targetId,patch),saved};
}
const patches=()=>trace.requests.filter((r:any)=>r.method==='PATCH'),members=()=>trace.requests.filter((r:any)=>r.table==='family_members');
async function success(options:Options,expected:Record<string,unknown>={}){const f=fixture(options);expect(await f.run()).toMatchObject({ok:true,data:{...f.saved,...expected}});expect(patches()).toHaveLength(1);expect(trace.activity).toEqual([{agent:'calendar',action:'update',title:'Updated "'+(expected.title??f.saved.title)+'"',href:'/dashboard/calendar',memberId:expected.assignee_id===undefined?f.saved.assignee_id:expected.assignee_id}]);return f;}
describe('original scoped Calendar UPDATE assignee admission',()=>{
 it('refuses an existing family-B assignee before a family-A event PATCH',async()=>{const f=fixture({patch:{assigneeId:ownB}});expect(await f.run()).toMatchObject({ok:false});expect(patches()).toEqual([]);expect(trace.activity).toEqual([]);});
 it('refuses an existing family-A assignee before a family-B event PATCH',async()=>{const f=fixture({family:B,patch:{assigneeId:ownA}});expect(await f.run()).toMatchObject({ok:false});expect(patches()).toEqual([]);expect(trace.activity).toEqual([]);});
 it('preserves a same-family-A assignee update',async()=>{await success({patch:{assigneeId:ownA}});expect(patches()[0].payload).toEqual({assignee_id:ownA});});
 it('preserves a same-family-B assignee update',async()=>{await success({family:B,patch:{assigneeId:ownB}});expect(patches()[0].payload).toEqual({assignee_id:ownB});});
 it('preserves an uppercase requested UUID through normalized saved member',async()=>{await success({patch:{assigneeId:ownA.toUpperCase()}},{assignee_id:ownA});expect(patches()[0].payload.assignee_id).toBe(ownA.toUpperCase());});
 it('preserves an uppercase server family UUID with normalized saved family',async()=>{await success({family:A.toUpperCase(),patch:{assigneeId:ownA}});expect(patches()[0].query.family_id).toBe('eq.'+A.toUpperCase());});
 it('preserves explicit null unassignment without member lookup',async()=>{await success({patch:{assigneeId:null}},{assignee_id:null});expect(members()).toEqual([]);expect(patches()[0].payload).toEqual({assignee_id:null});});
 it('preserves omitted assignee in a trimmed title patch without lookup',async()=>{await success({patch:{title:' Neutral renamed event '}},{title:'Neutral renamed event'});expect(members()).toEqual([]);expect(patches()[0].payload).toEqual({title:'Neutral renamed event'});});
 it('preserves unrelated location and description normalization without member lookup',async()=>{await success({patch:{location:' Neutral new room ',description:' '}},{location:'Neutral new room',description:null});expect(members()).toEqual([]);expect(patches()[0].payload).toEqual({location:'Neutral new room',description:null});});
 it('preserves target-not-found refusal with exact target id and family filters',async()=>{const f=fixture({patch:{title:'Neutral renamed event'},targetMissing:true});expect(await f.run()).toMatchObject({ok:false,code:'not_found'});expect(patches()).toHaveLength(1);expect(trace.activity).toEqual([]);});
 it('preserves foreign-target no-row refusal with server family filter',async()=>{const f=fixture({patch:{title:'Neutral renamed event'},targetForeign:true});expect(await f.run()).toMatchObject({ok:false,code:'not_found'});expect(patches()).toHaveLength(1);expect(trace.activity).toEqual([]);});
 it('preserves actual SDK PATCH403 refusal without activity',async()=>{const f=fixture({patch:{title:'Neutral renamed event'},writeStatus:403});expect(await f.run()).toMatchObject({ok:false,code:'db'});expect(patches()).toHaveLength(1);expect(trace.activity).toEqual([]);});
 it('preserves actual SDK PATCH500 refusal without activity',async()=>{const f=fixture({patch:{title:'Neutral renamed event'},writeStatus:500});expect(await f.run()).toMatchObject({ok:false,code:'db'});expect(patches()).toHaveLength(1);expect(trace.activity).toEqual([]);});
 it('preserves explicitly adapted data-plus-error precedence after actual healthy PATCH receipt',async()=>{const f=fixture({patch:{title:'Neutral renamed event'},dataError:true});expect(await f.run()).toMatchObject({ok:false,code:'db'});expect(patches()).toHaveLength(1);expect(trace.activity).toEqual([]);expect(trace.adapter).toBe('Actual healthy PATCH receipt → explicit data+error precedence adapter');});
 it('preserves no-op patch refusal before any SDK query',async()=>{const f=fixture({patch:{}});expect(await f.run()).toMatchObject({ok:false,code:'invalid_input'});expect(trace.requests).toEqual([]);expect(trace.activity).toEqual([]);});
 it('preserves empty title refusal before any SDK query',async()=>{const f=fixture({patch:{title:' '}});expect(await f.run()).toMatchObject({ok:false,code:'invalid_input'});expect(trace.requests).toEqual([]);expect(trace.activity).toEqual([]);});
 it('preserves invalid start-time refusal before any SDK query',async()=>{const f=fixture({patch:{startsAt:'neutral-invalid-time'}});expect(await f.run()).toMatchObject({ok:false,code:'invalid_input'});expect(trace.requests).toEqual([]);expect(trace.activity).toEqual([]);});
 it('preserves reversed explicit start-end range refusal before any SDK query',async()=>{const f=fixture({patch:{startsAt:'2026-01-02T11:00:00Z',endsAt:'2026-01-02T10:00:00Z'}});expect(await f.run()).toMatchObject({ok:false,code:'invalid_input'});expect(trace.requests).toEqual([]);expect(trace.activity).toEqual([]);});
 it('preserves normalized valid timestamps and category without member lookup',async()=>{await success({patch:{startsAt:'2026-01-03T10:00:00Z',endsAt:'2026-01-03T11:00:00Z',category:'general',allDay:true}},{starts_at:'2026-01-03T10:00:00.000Z',ends_at:'2026-01-03T11:00:00.000Z',all_day:true});expect(members()).toEqual([]);expect(patches()[0].payload).toEqual({starts_at:'2026-01-03T10:00:00.000Z',ends_at:'2026-01-03T11:00:00.000Z',category:'general',all_day:true});});
});

describe('UPDATE member-read refusal and SDK PATCH array compatibility',()=>{
 async function refused(options:Options){const f=fixture({patch:{assigneeId:ownA},...options});const result=await f.run();expect(result).toMatchObject({ok:false});expect(patches()).toEqual([]);expect(trace.activity).toEqual([]);return result;}
 it('refuses actual SDK member lookup403 before PATCH',async()=>{expect(await refused({memberStatus:403})).toMatchObject({code:'db'});});
 it('refuses successful empty member collection before PATCH',async()=>{await refused({memberBody:[]});});
 it('refuses successful null member receipt before PATCH',async()=>{await refused({memberBody:null});});
 it('refuses successful plain-object member receipt before PATCH',async()=>{await refused({memberBody:{}});});
 it('refuses successful string member receipt before PATCH',async()=>{await refused({memberBody:'neutral member receipt'});});
 it('refuses a returned wrong member id before PATCH',async()=>{await refused({memberBody:[{id:ownB,family_id:A}]});});
 it('refuses a returned wrong family id before PATCH',async()=>{await refused({memberBody:[{id:ownA,family_id:B}]});});
 it('preserves SDK multiple-member-row refusal before PATCH',async()=>{expect(await refused({memberBody:[{id:ownA,family_id:A},{id:ownA,family_id:A}]})).toMatchObject({code:'db'});});
 it('refuses a member receipt missing id before PATCH',async()=>{await refused({memberBody:[{family_id:A}]});});
 it('refuses a member receipt missing family id before PATCH',async()=>{await refused({memberBody:[{id:ownA}]});});
 it('preserves explicitly adapted member data-plus-error precedence before PATCH',async()=>{expect(await refused({memberDataError:true})).toMatchObject({code:'db'});expect(trace.adapter).toBe('Actual healthy member receipt → explicit data+error precedence adapter');});
 it('preserves actual SDK PATCH single-element-array normalization and activity',async()=>{await success({patch:{title:'Neutral renamed event'},patchArray:true},{title:'Neutral renamed event'});expect(members()).toEqual([]);expect(patches()).toHaveLength(1);});
 it('preserves actual SDK PATCH empty-array normalization to notfound',async()=>{const f=fixture({patch:{title:'Neutral renamed event'},patchEmpty:true});expect(await f.run()).toMatchObject({ok:false,code:'not_found'});expect(patches()).toHaveLength(1);expect(members()).toEqual([]);expect(trace.activity).toEqual([]);});
});
