import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';import {createClient} from '@supabase/supabase-js';import {afterAll,afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const sourceRoot=process.env.BUBALY_OPEN_CHORE_SOURCE_ROOT??process.cwd();
const sources=Object.fromEntries(Object.entries({tasks:'lib/services/tasks/index.ts',types:'lib/services/types.ts',errors:'lib/supabase/errors.ts'}).map(([k,p])=>[k,ts.transpileModule(fs.readFileSync(path.join(sourceRoot,p),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText]));
const traces:any[]=[];let trace:any;beforeEach(()=>{trace={name:expect.getState().currentTestName,requests:[],transportErrors:[],forbidden:[],settled:0,logs:[]};vi.spyOn(console,'error').mockImplementation((...args)=>trace.logs.push(args));});afterEach(()=>{traces.push(trace);expect(trace.forbidden).toEqual([]);expect(trace.transportErrors).toEqual([]);expect(trace.requests.length).toBe(1);expect(trace.settled).toBe(trace.requests.length);expect(trace.logs.every((a:any[])=>a[0]==='[service:tasks] open chores read failed')).toBe(true);vi.restoreAllMocks();});afterAll(()=>{if(process.env.BUBALY_OPEN_CHORE_TRACE)fs.writeFileSync(process.env.BUBALY_OPEN_CHORE_TRACE,JSON.stringify(traces,null,2)+'\n');});
function fixture(body:unknown,input:Record<string,unknown>={},refused=false,undefinedAdapter=false,serverError=false,dataErrorAdapter=false){const deny=(why:string):never=>{trace.forbidden.push(why);throw Error(why);};const transport:typeof fetch=async(resource,init)=>{try{const url=new URL(String(resource)),method=init?.method??'GET';if(url.origin!=='https://open-chore.invalid'||url.pathname!=='/rest/v1/chore_assignments'||method!=='GET'||trace.requests.length>=1)deny('Outside finite open chore collection');trace.requests.push({method,path:url.pathname,query:Object.fromEntries(url.searchParams)});return new Response(JSON.stringify(refused?{code:'42501',message:'Synthetic refused collection'}:serverError?{code:'XX000',message:'Synthetic collection unavailable'}:body),{status:refused?403:serverError?500:200,headers:{'content-type':'application/json'}});}catch(e){trace.transportErrors.push(String(e));throw e;}finally{trace.settled++;}};
 const sdk=createClient('https://open-chore.invalid','synthetic-key',{accessToken:async()=>null,auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},global:{fetch:transport}});let db:any=sdk;if(undefinedAdapter||dataErrorAdapter){db={from:(table:string)=>{let current:any=sdk.from(table);const proxy:any=new Proxy({},{get(_target,key){if(key==='then')return(resolve:any,reject:any)=>current.then((reply:any)=>resolve(dataErrorAdapter?{...reply,data:{neutral:'malformed success'},error:{code:'42501',message:'Synthetic denied collection'}}:{...reply,data:undefined}),reject);const value=Reflect.get(current,key,current);return typeof value==='function'?(...args:any[])=>{const result=value.apply(current,args);if(result&&typeof result==='object')current=result;return proxy;}:value;}});return proxy;}};trace.adapter=dataErrorAdapter?'Healthy actualSDK array reply → explicit data+error precedence adapter':'Healthy actualSDK null reply → typed legacy undefined data';}
 const cache:any={};function load(name:string):any{if(cache[name])return cache[name];const entry={exports:{}};cache[name]=entry.exports;const require=(id:string):any=>{if(id==='server-only')return{};if(id==='../scope')return{scopeNow:()=>deny('Unused scopeNow')};if(id==='@/lib/chores/respawn')return{nextChoreDueAt:()=>deny('Unused respawn'),choreRepeats:()=>deny('Unused respawn')};if(id==='@/lib/supabase/chunked-in')return{readAllInChunks:()=>deny('Unused readAllInChunks')};if(id==='../types')return load('types');if(id==='@/lib/supabase/errors')return load('errors');if(id==='../activity')return{recordActivitySafely:()=>deny('activity forbidden in read')};if(id==='../idempotency')return new Proxy({},{get:()=>()=>deny('idempotency unused')});if(id==='@/lib/supabase/escape-like')return{escapeLike:()=>deny('NS escapeLike unused; no query supplied')};if(id==='@/lib/i18n/server')return{getTranslations:()=>deny('i18n unused')};return deny('module import '+id);};new Function('require','module','exports',sources[name])(require,entry,entry.exports);cache[name]=entry.exports;return entry.exports;}
 const scope:any={db,familyId:'family-A',userId:'synthetic-user',memberId:null,role:'parent',actorKind:'member',tz:'UTC',now:new Date('2026-01-01T00:00:00Z')};return{run:()=>load('tasks').listOpenChores(scope,input),dbCode:()=>load('types').SERVICE_CODES.db};}
function wire(expected:Record<string,string>){expect(trace.requests).toHaveLength(1);expect(trace.requests[0].method).toBe('GET');expect(trace.requests[0].query).toEqual({select:'*',family_id:'eq.family-A',status:'in.(todo,in_progress,submitted)',order:'due_at.asc.nullslast',limit:'50',...expected});}
describe('original open chore collection admission',()=>{
 for(const [label,body]of [['indexed array-like object',{0:{id:'synthetic-A'},length:1}],['plain object',{neutral:'synthetic'}],['string','neutral synthetic collection'],['number',3],['boolean',true]] as const){it('refuses a successful non-array '+label,async()=>{const f=fixture(body);const result=await f.run();expect(result).toMatchObject({ok:false,code:f.dbCode()});expect(result).not.toHaveProperty('data');wire({});});}
 it('preserves a healthy neutral array',async()=>{const rows=[{id:'synthetic-A',chore_id:'synthetic-chore',member_id:'synthetic-member',status:'todo',family_id:'family-A'}];const f=fixture(rows);expect(await f.run()).toEqual({ok:true,data:rows});wire({});});
 it('preserves an empty array',async()=>{const f=fixture([]);expect(await f.run()).toEqual({ok:true,data:[]});wire({});});
 it('preserves null successful collection as empty',async()=>{const f=fixture(null);expect(await f.run()).toEqual({ok:true,data:[]});wire({});});
 it('preserves explicitly adapted legacy undefined collection as empty',async()=>{const f=fixture(null,{},false,true);expect(await f.run()).toEqual({ok:true,data:[]});expect(trace.adapter).toBeDefined();wire({});});
 it('preserves opaque array entries without a stricter row policy',async()=>{const rows=[null,'opaque',7,false,{neutral:'synthetic'}];const f=fixture(rows);expect(await f.run()).toEqual({ok:true,data:rows});wire({});});
 it('refuses actual SDK403 before usable data',async()=>{const f=fixture([],{},true);expect(await f.run()).toMatchObject({ok:false,code:f.dbCode()});wire({});});
 it('keeps server-family open-status and requested member in the GET',async()=>{const f=fixture([],{memberId:'synthetic-member',limit:12});expect(await f.run()).toEqual({ok:true,data:[]});wire({limit:'12',member_id:'eq.synthetic-member'});});
 it('clamps a zero limit to one',async()=>{const f=fixture([],{limit:0});expect(await f.run()).toEqual({ok:true,data:[]});wire({limit:'1'});});
 it('clamps an oversized limit to200',async()=>{const f=fixture([],{limit:500});expect(await f.run()).toEqual({ok:true,data:[]});wire({limit:'200'});});
 it('does not accept an injected family in the read input',async()=>{const f=fixture([],{familyId:'family-B'});expect(await f.run()).toEqual({ok:true,data:[]});wire({});});
});

describe('additional open chore collection controls',()=>{
 for(const [label,body]of [['zero',0],['false',false]] as const){it('refuses a successful non-array '+label,async()=>{const f=fixture(body);const result=await f.run();expect(result).toMatchObject({ok:false,code:f.dbCode()});expect(result).not.toHaveProperty('data');wire({});});}
 it('refuses actual SDK500 collection error',async()=>{const f=fixture([],{},false,false,true);const result=await f.run();expect(result).toMatchObject({ok:false,code:f.dbCode()});expect(result).not.toHaveProperty('data');wire({});});
 it('preserves explicit data+error adapter error precedence',async()=>{const f=fixture([],{},false,false,false,true);const result=await f.run();expect(result).toMatchObject({ok:false,code:f.dbCode()});expect(result).not.toHaveProperty('data');expect(trace.logs).toHaveLength(1);expect(trace.logs[0][1]).toMatchObject({code:'42501',message:'Synthetic denied collection'});expect(trace.adapter).toBe('Healthy actualSDK array reply → explicit data+error precedence adapter');wire({});});
});
