import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {createServer as createHttpServer} from 'node:http';
import {once} from 'node:events';
import {createClient} from '@supabase/supabase-js';
import type {Database} from '@/lib/database.types';
const h=vi.hoisted(()=>({db:null as unknown,writeError:null as string|null,writeAttempts:0,requests:[] as URL[],inserted:[] as Record<string,unknown>[],rate:vi.fn(),provider:vi.fn()}));
vi.mock('@/lib/i18n/server',()=>({getTranslations:async()=> (key:string)=>key}));
vi.mock('@/lib/supabase/auth',()=>({requireUserContext:async()=>({user:{id:'synthetic-user'},active:{familyId:'synthetic-family',role:'parent'}})}));
vi.mock('@/lib/supabase/server',()=>({createServer:async()=>h.db}));
vi.mock('@/lib/server/request-rate-limit',()=>({enforceRequestRateLimit:h.rate}));
vi.mock('@/lib/google-token-storage',()=>({decodeGoogleToken:()=>({legacy:false,token:{accessToken:'synthetic-token',refreshToken:null,expiresAt:9999999999999}}),encodeGoogleToken:()=>null,hasStoredGoogleToken:()=>true}));
import {fetchGoogleCalendarEvents,GOOGLE_CALENDAR_READ_LIMITS as LIMITS} from '@/lib/google';
import {POST} from '@/app/api/google/calendar/sync/route';
const nativeFetch=globalThis.fetch;
const event=(id:string)=>({id,summary:'Synthetic '+id,start:{dateTime:'2026-11-01T09:00:00-05:00'},end:{dateTime:'2026-11-01T10:00:00-05:00'}});
const read=()=>fetchGoogleCalendarEvents('synthetic-token','2026-10-08T00:00:00Z','2027-01-08T00:00:00Z');
beforeEach(()=>{
 vi.resetAllMocks();h.requests=[];h.inserted=[];h.writeError=null;h.writeAttempts=0;h.rate.mockResolvedValue({ok:true});h.provider.mockImplementation(()=>Response.json({kind:'calendar#events',items:[event('A')]}));vi.spyOn(console,'error').mockImplementation(()=>{});
 vi.stubGlobal('fetch',vi.fn(async(input,init)=>{const url=new URL(String(input));expect(url.origin).toBe('https://www.googleapis.com');expect(url.pathname).toBe('/calendar/v3/calendars/primary/events');expect(new Headers(init?.headers).get('Authorization')).toBe('Bearer synthetic-token');expect(init?.signal).toBeInstanceOf(AbortSignal);h.requests.push(url);return h.provider(url,h.requests.length,init);}));
 h.db=createClient<Database>('https://synthetic-google-db.invalid','synthetic-key',{auth:{persistSession:false,autoRefreshToken:false},global:{fetch:async(input,init)=>{const url=new URL(String(input));expect(url.origin).toBe('https://synthetic-google-db.invalid');if(url.pathname==='/rest/v1/user_preferences'){expect(url.searchParams.get('user_id')).toBe('eq.synthetic-user');return Response.json({notification_prefs:{googleCalendarToken:'synthetic'}});}expect(url.pathname).toBe('/rest/v1/calendar_events');expect(init?.method).toBe('POST');h.writeAttempts++;if(h.writeError)return Response.json({code:h.writeError,message:'Synthetic atomic insert refused'},{status:409});h.inserted.push(...JSON.parse(String(init?.body)));return new Response(null,{status:201});}}});
});
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();vi.restoreAllMocks();});
function pages(count:number,cap:number){h.provider.mockImplementation((url:URL)=>{const offset=Number(url.searchParams.get('pageToken')??0);const end=Math.min(offset+cap,count);return Response.json({kind:'calendar#events',items:Array.from({length:end-offset},(_,i)=>event(String(offset+i))),...(end<count?{nextPageToken:String(end)}:{})});});}
async function refused(){const response=await POST();expect(response.status).toBe(503);expect(await response.json()).toEqual({error:'sync.syncFailed'});expect(h.inserted).toEqual([]);}
describe('actual provider fetch → complete Google helper → route → SDK',()=>{
 it.each([[253,250],[61,2]])('imports every %i event despite provider cap%i',async(count,cap)=>{pages(count,cap);const response=await POST();expect(response.status).toBe(200);expect(await response.json()).toEqual({synced:count});expect(h.inserted).toHaveLength(count);expect(new Set(h.inserted.map(row=>row.title)).size).toBe(count);expect(h.inserted.every(row=>row.family_id==='synthetic-family'&&row.created_by==='synthetic-user')).toBe(true);expect(h.requests).toHaveLength(Math.ceil(count/cap));const first=h.requests[0];for(const request of h.requests){for(const key of ['timeMin','timeMax','singleEvents','orderBy','maxResults','calendarId'])expect(request.searchParams.get(key)).toBe(first.searchParams.get(key));expect(request.searchParams.get('singleEvents')).toBe('true');expect(request.searchParams.get('orderBy')).toBe('startTime');}expect(h.requests[1].searchParams.get('pageToken')).toBe(String(cap));});
 it('preserves original offset instants, civil DATE, text and explicit ends',async()=>{h.provider.mockImplementation(()=>Response.json({kind:'calendar#events',items:[{...event('timed'),description:'Line one\nLine two',location:'Hall; east'},{id:'date',summary:'Civil day',start:{date:'2026-11-01'},end:{date:'2026-11-03'}}]}));expect((await POST()).status).toBe(200);expect(h.inserted[0]).toMatchObject({starts_at:'2026-11-01T09:00:00-05:00',ends_at:'2026-11-01T10:00:00-05:00',description:'Line one\nLine two',location:'Hall; east',all_day:false});expect(h.inserted[1]).toMatchObject({starts_at:'2026-11-01',ends_at:'2026-11-03',all_day:true});});
 it.each([{kind:'calendar#events'}, {kind:'calendar#events',items:[]}])('accepts a legitimate empty terminal page %j',async body=>{h.provider.mockImplementation(()=>Response.json(body));const response=await POST();expect(response.status).toBe(200);expect(await response.json()).toEqual({synced:0});expect(h.inserted).toEqual([]);expect(h.requests).toHaveLength(1);});
 it('keeps an empty intermediate page with a valid continuation instead of declaring completion',async()=>{h.provider.mockImplementation((_url:URL,n:number)=>Response.json(n===1?{kind:'calendar#events',nextPageToken:'second'}:{kind:'calendar#events',items:[event('C')]}));expect((await read()).map(row=>row.id)).toEqual(['C']);expect(h.requests).toHaveLength(2);});
 it('does not mistake a full terminal page for truncation',async()=>{pages(250,250);expect(await read()).toHaveLength(250);expect(h.requests).toHaveLength(1);});
 it.each(['403','network','invalid-json','unreadable','page-bytes','duplicate','repeat-token','null-token','blank-token','token-length','malformed-page','malformed-item','invalid-date','mixed-clock','reversed','cancelled','text-type','oversized-page'])('refuses all native writes after a later %s failure',async kind=>{
  h.provider.mockImplementation((_url:URL,n:number)=>{
   if(n===1)return Response.json({kind:'calendar#events',items:[event('A')],nextPageToken:'second'});
   if(kind==='403')return new Response(null,{status:403});if(kind==='network')throw new TypeError('Synthetic network failure');if(kind==='invalid-json')return new Response('{');if(kind==='unreadable')return new Response(new ReadableStream({start(controller){controller.error(new Error('Synthetic body failure'));}}));if(kind==='page-bytes')return new Response('{}',{headers:{'Content-Length':String(LIMITS.pageBytes+1)}});
   if(kind==='duplicate')return Response.json({kind:'calendar#events',items:[event('A')]});if(kind==='repeat-token')return Response.json({kind:'calendar#events',items:[event('B')],nextPageToken:'second'});if(kind==='null-token')return Response.json({kind:'calendar#events',items:[event('B')],nextPageToken:null});if(kind==='blank-token')return Response.json({kind:'calendar#events',items:[event('B')],nextPageToken:' '});if(kind==='token-length')return Response.json({kind:'calendar#events',items:[event('B')],nextPageToken:'x'.repeat(4097)});if(kind==='malformed-page')return Response.json({kind:'calendar#events',items:{}});if(kind==='malformed-item')return Response.json({kind:'calendar#events',items:[{...event('B'),id:''}]});if(kind==='oversized-page')return Response.json({kind:'calendar#events',items:Array.from({length:251},(_,i)=>event(String(i)))});
   const invalid=kind==='invalid-date'?{start:{date:'2026-02-30'},end:{date:'2026-03-01'}}:kind==='mixed-clock'?{end:{date:'2026-11-02'}}:kind==='reversed'?{end:{dateTime:'2026-11-01T08:00:00-05:00'}}:kind==='cancelled'?{status:'cancelled'}:{summary:42};return Response.json({kind:'calendar#events',items:[{...event('B'),...invalid}]});
  });await refused();expect(h.requests).toHaveLength(2);
 });
 it.each([{error:{code:403,message:'Synthetic denial'}},{kind:'calendar#events',error:{code:403,message:'Synthetic denial'}},{kind:'calendar#event',items:[]},{items:[]},{}])('refuses later HTTP200 invalid collection envelope %j before any inserts',async body=>{
  h.provider.mockImplementation((_url:URL,n:number)=>Response.json(n===1?{kind:'calendar#events',items:[event('A')],nextPageToken:'second'}:body));await refused();expect(h.requests).toHaveLength(2);expect(h.writeAttempts).toBe(0);
 });
 it.each([null,[],{kind:'calendar#events',items:null},{kind:'calendar#events',items:[null]},{kind:'calendar#events',items:[event('A'),event('A')]},{kind:'calendar#events',items:[{...event('A'),start:{dateTime:'2026-11-01T09:00:00'}}]},{kind:'calendar#events',items:[{...event('A'),start:{dateTime:'2026-02-30T09:00:00Z'}}]},{kind:'calendar#events',items:[{...event('A'),start:{dateTime:'2026-11-01T24:00:00Z'}}]}])('refuses malformed initial collection %j before inserts',async body=>{h.provider.mockImplementation(()=>Response.json(body));await refused();});
 it('accepts exactly the total event bound on a terminal page',async()=>{pages(LIMITS.events,LIMITS.page);expect(await read()).toHaveLength(LIMITS.events);expect(h.requests).toHaveLength(LIMITS.events/LIMITS.page);});
 it('refuses a later event beyond the total bound before any native inserts',async()=>{pages(LIMITS.events+1,LIMITS.page);await refused();expect(h.requests).toHaveLength(LIMITS.events/LIMITS.page+1);});
 it('refuses a unique-token infinite sequence at the explicit page bound',async()=>{h.provider.mockImplementation((_url:URL,n:number)=>Response.json({kind:'calendar#events',items:[],nextPageToken:'page-'+n}));await refused();expect(h.requests).toHaveLength(LIMITS.pages);});
 it('refuses cumulative response bytes even if every page fits its individual budget',async()=>{const padding='x'.repeat(LIMITS.pageBytes-300);h.provider.mockImplementation((_url:URL,n:number)=>Response.json({kind:'calendar#events',items:[event(String(n))],nextPageToken:'page-'+n,padding}));await refused();expect(h.requests).toHaveLength(9);});
 it.each([['junk','2027-01-08T00:00:00Z'],['2026-02-30T00:00:00Z','2027-01-08T00:00:00Z'],['2027-01-08T00:00:00Z','2026-10-08T00:00:00Z']])('rejects invalid query window %s %s before fetch',async(from,to)=>{await expect(fetchGoogleCalendarEvents('synthetic-token',from,to)).rejects.toThrow();expect(h.requests).toEqual([]);});
 it('refuses a later aborted provider request before native insertion',async()=>{h.provider.mockImplementation((_url:URL,n:number)=>{if(n===1)return Response.json({kind:'calendar#events',items:[event('A')],nextPageToken:'second'});throw new DOMException('Synthetic deadline expired','TimeoutError');});await refused();expect(h.requests).toHaveLength(2);});
 it.each(['23505','42501'])('does not report success after atomic insert refusal %s',async(code)=>{h.writeError=code;const response=await POST();expect(h.writeAttempts).toBe(1);expect(h.inserted).toEqual([]);expect(response.status).toBe(500);expect(await response.json()).toEqual({error:'sync.couldNotSaveImportedCalendar'});});
 it('aborts a stalled later HTTP response body using the actual shared deadline before insertion',async()=>{
  const timeout=AbortSignal.timeout.bind(AbortSignal);const timeoutSpy=vi.spyOn(AbortSignal,'timeout').mockImplementation(ms=>timeout(ms===60_000?300:5000));const signals:AbortSignal[]=[];
  let calls=0;const server=createHttpServer((_request,response)=>{calls++;response.writeHead(200,{'Content-Type':'application/json'});if(calls===1)response.end(JSON.stringify({kind:'calendar#events',items:[event('A')],nextPageToken:'second'}));else response.write('{"items":[');});
  server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();expect(address&&typeof address==='object').toBe(true);if(!address||typeof address==='string')throw new Error('Missing synthetic loopback port');
  h.provider.mockImplementation((url:URL,_n:number,init:RequestInit)=>{signals.push(init.signal as AbortSignal);return nativeFetch(`http://127.0.0.1:${address.port}${url.pathname}${url.search}`,init);});
  try{await refused();expect(calls).toBe(2);expect(h.writeAttempts).toBe(0);expect(h.requests).toHaveLength(2);expect(signals[1].aborted).toBe(true);expect(timeoutSpy.mock.calls.map(([ms])=>ms)).toEqual([60_000,15_000,15_000]);}finally{server.closeAllConnections();await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}
 });
 it('preserves rate refusal before provider calls or native inserts',async()=>{h.rate.mockResolvedValue({ok:false,retryAfter:17});const response=await POST();expect(response.status).toBe(429);expect(response.headers.get('Retry-After')).toBe('17');expect(h.requests).toEqual([]);expect(h.inserted).toEqual([]);});
});
