import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';import {createClient} from '@supabase/supabase-js';import {afterAll,afterEach,beforeEach,describe,expect,it} from 'vitest';
const source=fs.existsSync(path.join(process.cwd(),'source/components/modules/inventory-module.tsx'))?path.join(process.cwd(),'source'):process.cwd(),moduleText=fs.readFileSync(path.join(source,'components/modules/inventory-module.tsx'),'utf8'),helperText=fs.readFileSync(path.join(source,'lib/supabase/read-all.ts'),'utf8');
const ast=ts.createSourceFile('inventory-module.tsx',moduleText,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let callback:ts.Expression|undefined;let matched=0;function visit(n:ts.Node){if(ts.isCallExpression(n)&&n.expression.getText(ast)==='useRealtimeQuery'&&n.arguments.length){const arg=n.arguments[0];if(ts.isObjectLiteralExpression(arg)&&arg.properties.some(p=>ts.isPropertyAssignment(p)&&p.name.getText(ast)==='table'&&ts.isStringLiteral(p.initializer)&&p.initializer.text==='inventory_items')){const property=arg.properties.find(p=>ts.isPropertyAssignment(p)&&p.name.getText(ast)==='fetcher');if(property&&ts.isPropertyAssignment(property)){callback=property.initializer;matched++;}}}ts.forEachChild(n,visit);}visit(ast);if(matched!==1||!callback)throw Error('Expected single exact Inventory items fetcher');
const compile=(s:string)=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText,helper={exports:{} as any};new Function('module','exports',compile(helperText))(helper,helper.exports);const extraction=callback.getText(ast),compiled=compile('export const fetcher = '+extraction+';'),traces:any[]=[];let trace:any;const protocol=extraction.includes('readAllAsQuery')?'offset':extraction.includes('readInventoryItems')?'cursor':null;if(!protocol)throw Error('Undeclared Inventory reader protocol');let domainReader:any;if(protocol==='cursor'){const entry={exports:{} as any};new Function('require','module','exports',compile(fs.readFileSync(path.join(source,'lib/inventory/read-items.ts'),'utf8')))((id:string)=>{if(id==='@/lib/supabase/read-all'||id==='../supabase/read-all')return helper.exports;throw Error('Unapproved domain reader import '+id);},entry,entry.exports);domainReader=entry.exports.readInventoryItems;}
const initial=['A','B','C','D','E'].map((id,i)=>({id,family_id:'family-A',name:'Synthetic '+id,updated_at:'2026-10-02T0'+(5-i)+':00:00.000Z'}));
beforeEach(()=>{trace={name:expect.getState().currentTestName,requests:[],settled:0,transportErrors:[],forbidden:[],mutation:null};});afterEach(()=>{traces.push(trace);expect(trace.transportErrors).toEqual([]);expect(trace.forbidden).toEqual([]);expect(trace.requests.length).toBeLessThanOrEqual(8);expect(trace.settled).toBe(trace.requests.length);if(!trace.directModel){let received=0;for(let i=0;i<trace.requests.length;i++){const first=(trace.readStarts??[0]).includes(i);if(first)received=0;const r=trace.requests[i];expect(r.order).toBe(protocol==='offset'?'updated_at.desc,id.desc':'id.asc');expect(r.offset).toBe(protocol==='offset'?received:0);expect(r.idPredicate).toBe(protocol==='offset'||first?null:'gt.'+trace.requests[i-1].delivered.at(-1));received+=r.delivered.length;}}});afterAll(()=>{if(process.env.BUBALY_INV_OFFSET_TRACE)fs.writeFileSync(process.env.BUBALY_INV_OFFSET_TRACE,JSON.stringify({extraction,compiled,protocol,executedReadAllFunction:helper.exports.readAll.toString(),traces},null,2)+'\n');});
function fixture(mode='static',cap=2){let rows=initial.map(x=>({...x}));if(mode==='legacy-values')rows=rows.map((x,i)=>({...x,updated_at:String(5-i).padStart(4,'0')}));if(mode==='legacy-ties')rows=rows.map(x=>({...x,updated_at:'same'}));if(mode==='microseconds')rows=rows.map((x,i)=>({...x,updated_at:'2026-10-02T05:00:00.12300'+[1,2,1,2,3][i]+'Z'}));if(mode==='equal-ties')rows=rows.map(x=>({...x,updated_at:'2026-10-02T05:00:00.123456Z'}));if(mode==='foreign')rows.push({id:'FOREIGN',family_id:'family-B',name:'Synthetic foreign',updated_at:'2026-10-02T09:00:00.000Z'});let reads=0;const transport:typeof fetch=async(input,init)=>{try{const u=new URL(String(input)),method=init?.method??'GET';if(u.origin!=='https://inventory-offset.invalid'||u.pathname!=='/rest/v1/inventory_items'||method!=='GET'||u.searchParams.get('select')!=='*'||u.searchParams.get('family_id')!=='eq.family-A'||!['updated_at.desc,id.desc','id.asc'].includes(u.searchParams.get('order')??'')||trace.requests.length>=8){trace.forbidden.push('Unexpected SDK request');throw Error('Outside Inventory read model');}const offset=Number(u.searchParams.get('offset')??0),limit=Number(u.searchParams.get('limit'));if(!Number.isInteger(offset)||offset<0||!Number.isInteger(limit)||limit<1)throw Error('Invalid range model');const idPredicate=u.searchParams.get('id'),order=u.searchParams.get('order');if(idPredicate&&(!idPredicate.startsWith('gt.')||order!=='id.asc'))throw Error('Unexpected cursor predicate');const scoped=rows.filter(x=>x.family_id==='family-A'&&(mode==='ignored-cursor'||!idPredicate||x.id>idPredicate.slice(3)));const ordered=scoped.sort((a,b)=>order==='id.asc'?(a.id<b.id?-1:a.id>b.id?1:0):a.updated_at===b.updated_at?(a.id>b.id?-1:a.id<b.id?1:0):(a.updated_at>b.updated_at?-1:1)),delivered=ordered.slice(offset,offset+Math.min(limit,cap)).map(x=>({...x}));reads++;trace.requests.push({method,query:u.search,offset,limit,order,idPredicate,delivered:delivered.map(x=>x.id)});
if(reads===1){if(mode==='behindinsert')rows.push({id:'AA',family_id:'family-A',name:'Synthetic behind cursor',updated_at:'2026-10-02T09:00:00.000Z'});if(mode==='frontinsert')rows.push({id:'X',family_id:'family-A',name:'Synthetic inserted',updated_at:'2026-10-02T09:00:00.000Z'});if(mode==='frontdelete')rows=rows.filter(x=>x.id!=='A');if(mode==='frontupdate')rows=rows.map(x=>x.id==='E'?{...x,updated_at:'2026-10-02T09:00:00.000Z'}:x);if(mode==='tailinsert')rows.push({id:'Z',family_id:'family-A',name:'Synthetic tail',updated_at:'2026-10-02T00:00:00.000Z'});if(mode==='taildelete')rows=rows.filter(x=>x.id!=='E');if(mode!=='static'&&mode!=='foreign'&&mode!=='later403')trace.mutation=mode;}
trace.settled++;if(mode==='null-body'||mode==='http204'){trace.requests.at(-1).delivered=[];return new Response(mode==='http204'?null:'null',{status:mode==='http204'?204:200,headers:{'content-type':'application/json'}});}return new Response(JSON.stringify(mode==='later403'&&reads===2?{code:'42501',message:'Synthetic read refused'}:delivered),{status:mode==='later403'&&reads===2?403:200,headers:{'content-type':'application/json'}});
}catch(e){trace.transportErrors.push(String(e));throw e;}};const db=createClient('https://inventory-offset.invalid','synthetic-public-key',{accessToken:async()=>null,global:{fetch:transport},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),entry={exports:{} as any};new Function('module','exports','readAllAsQuery','readInventoryItems','familyId',compiled)(entry,entry.exports,helper.exports.readAllAsQuery,domainReader,'family-A');return{raw:db,read:()=>{trace.readStarts??=[];trace.readStarts.push(trace.requests.length);return entry.exports.fetcher(db);},current:()=>rows.filter(x=>x.family_id==='family-A').map(x=>x.id)};}
function healthy(result:any,expected:string[]){expect(result.error).toBeNull();expect(result.truncated).toBe(false);expect(result.count).toBeNull();expect(result.data.map((x:any)=>x.id)).toEqual(expected);expect(new Set(result.data.map((x:any)=>x.id)).size).toBe(result.data.length);}
describe('original Inventory actual fetcher ordered offset mutation',()=>{
it('front insert must not duplicate a previously delivered existing row',async()=>{const f=fixture('frontinsert'),r=await f.read();trace.result=r;trace.current=f.current();expect(r.error).toBeNull();expect(r.truncated).toBe(false);expect(new Set(r.data.map((x:any)=>x.id)).size).toBe(r.data.length);});
it('front deletion must not skip a still-existing row after the first page',async()=>{const f=fixture('frontdelete'),r=await f.read();trace.result=r;trace.current=f.current();expect(r.error).toBeNull();expect(r.truncated).toBe(false);expect(f.current().every(id=>r.data.some((x:any)=>x.id===id))).toBe(true);});
it('existing tail row moving to newest must not disappear or duplicate another existing row',async()=>{const f=fixture('frontupdate'),r=await f.read();trace.result=r;trace.current=f.current();expect(r.error).toBeNull();expect(r.truncated).toBe(false);expect.soft(f.current().every(id=>r.data.some((x:any)=>x.id===id))).toBe(true);expect.soft(new Set(r.data.map((x:any)=>x.id)).size).toBe(r.data.length);});
it('unchanged cap2 catalog delivers every existing family row once through empty terminal page',async()=>{const f=fixture();healthy(await f.read(),['A','B','C','D','E']);expect(trace.requests.map((r:any)=>r.offset)).toEqual(protocol==='offset'?[0,2,4,5]:[0,0,0,0]);expect(trace.requests.map((r:any)=>r.idPredicate)).toEqual(protocol==='offset'?[null,null,null,null]:[null,'gt.B','gt.D','gt.E']);});
it('unchanged cap1 catalog advances by actual received rows',async()=>{const f=fixture('static',1);healthy(await f.read(),['A','B','C','D','E']);expect(trace.requests.map((r:any)=>r.offset)).toEqual(protocol==='offset'?[0,1,2,3,4,5]:[0,0,0,0,0,0]);expect(trace.requests.map((r:any)=>r.idPredicate)).toEqual(protocol==='offset'?[null,null,null,null,null,null]:[null,'gt.A','gt.B','gt.C','gt.D','gt.E']);});
it('tail insertion does not shift earlier offsets and remains delivered',async()=>{const f=fixture('tailinsert');healthy(await f.read(),['A','B','C','D','E','Z']);});
it('undelivered tail deletion does not skip surviving existing rows',async()=>{const f=fixture('taildelete');healthy(await f.read(),['A','B','C','D']);});
it('foreign-family newest row is excluded by every actual SDK page filter',async()=>{const f=fixture('foreign');healthy(await f.read(),['A','B','C','D','E']);});
it('later HTTP403 refuses partial rows instead of admitting incomplete success',async()=>{const f=fixture('later403'),r=await f.read();expect(r.data).toBeNull();expect(r.error).toMatchObject({code:'42501'});expect(trace.requests).toHaveLength(2);});
});

async function rawPage(f:any,cursor?:string){trace.directModel=true;let q=f.raw.from('inventory_items').select('*').eq('family_id','family-A').order('id',{ascending:true});if(cursor!==undefined)q=q.gt('id',cursor);return q.range(0,999);}
describe('declared finite stable id cursor model guards',()=>{
it('id ascending cursor excludes previous ids and resumes exactly after the last delivered id',async()=>{const f=fixture(),first=await rawPage(f),second=await rawPage(f,'B'),third=await rawPage(f,'D'),empty=await rawPage(f,'E');expect([first.data,second.data,third.data,empty.data].map(rows=>rows?.map((x:any)=>x.id))).toEqual([['A','B'],['C','D'],['E'],[]]);expect([first,second,third,empty].every(r=>r.error===null)).toBe(true);expect(trace.requests.map((r:any)=>r.idPredicate)).toEqual([null,'gt.B','gt.D','gt.E']);expect(trace.requests.map((r:any)=>r.offset)).toEqual([0,0,0,0]);});
it('deleting an already delivered front id does not shift later cursor matches',async()=>{const f=fixture('frontdelete');const first=await rawPage(f),second=await rawPage(f,'B'),third=await rawPage(f,'D');expect([first.data,second.data,third.data].flat().map((x:any)=>x.id)).toEqual(['A','B','C','D','E']);expect(second.data?.map((x:any)=>x.id)).toEqual(['C','D']);expect(f.current()).toEqual(['B','C','D','E']);});
it('updated_at moving an existing tail row leaves stable id cursor admission unchanged',async()=>{const f=fixture('frontupdate');await rawPage(f);const second=await rawPage(f,'B'),third=await rawPage(f,'D');expect([second.data,third.data].flat().map((x:any)=>x.id)).toEqual(['C','D','E']);expect(third.data?.[0].updated_at).toBe('2026-10-02T09:00:00.000Z');});
it('a newly inserted id ahead of the cursor is delivered without duplicating the first page',async()=>{const f=fixture('frontinsert'),first=await rawPage(f),second=await rawPage(f,'B'),third=await rawPage(f,'D'),empty=await rawPage(f,'X');expect([first.data,second.data,third.data,empty.data].flat().map((x:any)=>x.id)).toEqual(['A','B','C','D','E','X']);});
it('an id inserted behind the cursor is explicitly outside any snapshot guarantee',async()=>{const f=fixture('behindinsert'),first=await rawPage(f),second=await rawPage(f,'B'),third=await rawPage(f,'D');expect([first.data,second.data,third.data].flat().map((x:any)=>x.id)).toEqual(['A','B','C','D','E']);expect(f.current()).toContain('AA');expect(second.data?.map((x:any)=>x.id)).toEqual(['C','D']);});
it('foreign-family rows stay excluded when id cursor is supplied',async()=>{const f=fixture('foreign'),result=await rawPage(f,'D');expect(result.error).toBeNull();expect(result.data?.map((x:any)=>x.id)).toEqual(['E']);expect(trace.requests[0].query).toContain('family_id=eq.family-A');});
it('a later HTTP403 remains an SDK refusal under the cursor protocol',async()=>{const f=fixture('later403');await rawPage(f);const result=await rawPage(f,'B');expect(result.data).toBeNull();expect(result.error).toMatchObject({code:'42501'});expect(trace.requests).toHaveLength(2);});
});

describe('Inventory required final display timestamp and stable id ordering',()=>{
it('same millisecond but distinct PostgreSQL microsecond timestamps remain correctly descending',async()=>{const f=fixture('microseconds');healthy(await f.read(),['E','D','B','C','A']);});
it('truly equal timestamps retain stable id descending tie order',async()=>{const f=fixture('equal-ties');healthy(await f.read(),['E','D','C','B','A']);});
});

describe('Inventory per-read cursor lifetime and compatibility controls',()=>{
it('each complete reread starts a new cursor rather than reusing the terminal cursor',async()=>{const f=fixture();healthy(await f.read(),['A','B','C','D','E']);healthy(await f.read(),['A','B','C','D','E']);expect(trace.readStarts).toEqual([0,4]);expect(trace.requests[4].offset).toBe(0);expect(trace.requests[4].idPredicate).toBeNull();});
it('legacy non-ISO synthetic timestamps retain their existing descending display order',async()=>{const f=fixture('legacy-values');healthy(await f.read(),['A','B','C','D','E']);});
it('legacy non-ISO equal timestamps retain stable descending id ties',async()=>{const f=fixture('legacy-ties');healthy(await f.read(),['E','D','C','B','A']);});
it('an ignored cursor predicate cannot make the new cursor algorithm loop or publish duplicate partial rows',async()=>{const f=fixture('ignored-cursor'),r=await f.read();if(protocol==='cursor'){expect(r.data).toBeNull();expect(r.error).toMatchObject({message:'The inventory cursor did not advance'});expect(trace.requests).toHaveLength(2);}else{healthy(r,['A','B','C','D','E']);expect(trace.requests).toHaveLength(4);}expect(trace.requests.length).toBeLessThanOrEqual(4);});
});

describe('Inventory preserved actual SDK nullish terminal compatibility',()=>{
it('HTTP200 null collection retains the existing unavailable-page refusal',async()=>{const f=fixture('null-body'),r=await f.read();expect(r.data).toBeNull();expect(r.error?.message).toMatch(/page was unavailable/);expect(r.truncated).toBe(false);expect(r.count).toBeNull();expect(trace.requests).toHaveLength(1);});
it('HTTP204 empty response retains the existing unavailable-page refusal',async()=>{const f=fixture('http204'),r=await f.read();expect(r.data).toBeNull();expect(r.error?.message).toMatch(/page was unavailable/);expect(r.truncated).toBe(false);expect(r.count).toBeNull();expect(trace.requests).toHaveLength(1);});
});
