import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {createMove} from '@/lib/services/moving';
const {activity}=vi.hoisted(()=>({activity:[] as any[]}));
vi.mock('@/lib/services/activity',()=>({recordActivitySafely:async(_scope:any,input:any)=>{activity.push(input)}}));
vi.mock('@/lib/services/scope',()=>({scopeNow:()=>{throw Error('Unapproved default clock')},dayKeyInTz:()=>{throw Error('Unapproved default day')}}));
const {createClient}=createRequire(import.meta.url)('@supabase/supabase-js');
const FAMILY='synthetic-family-A';
const OLD={id:'synthetic-move-A',family_id:FAMILY,title:'Move to Maple St',move_date:'2026-11-03',status:'planning'};
const INPUT={title:'Another ordinary move',moveDate:'2026-12-01',hasKids:false,hasPets:false};
let proof:any;let log:any;
beforeEach(()=>{activity.length=0;proof={name:expect.getState().currentTestName,requests:[],replies:[],sdkReplies:[],fixtureErrors:[],forbidden:[],activity};log=vi.spyOn(console,'error').mockImplementation(()=>{});});
afterEach(()=>{log.mockRestore();expect(proof.fixtureErrors).toEqual([]);expect(proof.forbidden).toEqual([]);expect(proof.requests.length).toBeLessThanOrEqual(2);expect(proof.requests.every((r:any)=>r.table==='moves'&&['GET','POST'].includes(r.method))).toBe(true);if(process.env.BUBALY_MOVING_READ_RECEIPTS)fs.appendFileSync(process.env.BUBALY_MOVING_READ_RECEIPTS,JSON.stringify(proof)+'\n');});
function scenario(readBody:unknown,options:{readStatus?:number;postStatus?:number;undefinedAdapter?:boolean}={}){
 const db=createClient('https://moving-open-read.invalid','synthetic-public-key',{accessToken:async()=>null,auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},global:{fetch:async(input:any,init:any={})=>{try{
  const u=new URL(String(input)),method=init.method??'GET';if(u.origin!=='https://moving-open-read.invalid'||u.pathname!=='/rest/v1/moves'||!['GET','POST'].includes(method)||proof.requests.length>=2){proof.forbidden.push(String(input));throw Error('Unapproved finite moving transport');}
  const payload=init.body?JSON.parse(String(init.body)):null;proof.requests.push({table:'moves',method,query:u.search,payload});
  if(method==='GET'){expect(u.searchParams.get('family_id')).toBe('eq.'+FAMILY);expect(u.searchParams.get('limit')).toBe('1');expect(u.searchParams.get('select')).toBe('*');expect(u.searchParams.get('status')).toBe('in.(planning,packing,moving_day,settling)');proof.replies.push({method,body:readBody,status:options.readStatus??200});return new Response(JSON.stringify(readBody),{status:options.readStatus??200,headers:{'content-type':'application/json'}});}
  expect(payload.family_id).toBe(FAMILY);expect(payload.has_kids).toBe(false);expect(payload.has_pets).toBe(false);expect(payload.move_date).toBe(INPUT.moveDate);
  const body=options.postStatus?{code:'42501',message:'Synthetic move write refused'}:{...payload,id:'synthetic-new-move',status:'planning'};proof.replies.push({method,body,status:options.postStatus??201});return new Response(JSON.stringify(body),{status:options.postStatus??201,headers:{'content-type':'application/json'}});
 }catch(error){proof.fixtureErrors.push(error instanceof Error?error.message:String(error));throw error;}}}});
 {const from=db.from.bind(db);const wrap=(builder:any):any=>new Proxy(builder,{get(target,key){const value=Reflect.get(target,key,target);if(key==='then')return(resolve:any,reject:any)=>value.call(target,(reply:any)=>{proof.sdkReplies.push({method:target.method,data:reply.data,error:reply.error,status:reply.status});return resolve(options.undefinedAdapter&&target.method==='GET'?{...reply,data:undefined}:reply)},reject);if(typeof value==='function')return(...args:any[])=>{const next=value.apply(target,args);return next&&typeof next==='object'&&'then' in next?wrap(next):next;};return value;}});db.from=(...args:any[])=>wrap(from(...args));}
 const scope:any={db,familyId:FAMILY,userId:'synthetic-user',memberId:'synthetic-member',role:'parent',actorKind:'member',tz:'UTC'};return scope;
}
for(const [name,body] of [['plain object',{}],['length-zero object',{length:0}],['number',42],['boolean',false],['string','X'],['indexed object',{0:OLD,length:1}]] as const){it('malformed successful open-move '+name+' is refused before any create POST',async()=>{const result=await createMove(scenario(body),INPUT);proof.result=result;expect.soft(result.ok).toBe(false);expect(proof.requests.filter((r:any)=>r.method==='POST')).toHaveLength(0);expect.soft(activity).toHaveLength(0);});}
it('empty collection permits one scoped POST and reports created',async()=>{const result=await createMove(scenario([]),INPUT);proof.result=result;expect(result).toMatchObject({ok:true,data:{created:true,move:{family_id:FAMILY,title:INPUT.title}}});expect(proof.requests.map((r:any)=>r.method)).toEqual(['GET','POST']);expect(activity).toHaveLength(1);});
it('existing array returns its first move without any POST',async()=>{const result=await createMove(scenario([OLD]),INPUT);proof.result=result;expect(result).toEqual({ok:true,data:{move:OLD,created:false}});expect(proof.requests.map((r:any)=>r.method)).toEqual(['GET']);expect(activity).toHaveLength(0);});
it('null receipt preserves current intentional empty fallback',async()=>{const result=await createMove(scenario(null),INPUT);proof.result=result;expect(result).toMatchObject({ok:true,data:{created:true}});expect(proof.requests.map((r:any)=>r.method)).toEqual(['GET','POST']);});
it('undefined adapter over healthy actual SDK GET preserves empty fallback',async()=>{const result=await createMove(scenario([],{undefinedAdapter:true}),INPUT);proof.result=result;expect(result).toMatchObject({ok:true,data:{created:true}});expect(proof.replies[0].body).toEqual([]);expect(proof.requests.map((r:any)=>r.method)).toEqual(['GET','POST']);});
it('opaque later array entries preserve first-row behavior without row schema policy',async()=>{const result=await createMove(scenario([OLD,null,7,'opaque']),INPUT);proof.result=result;expect(result).toEqual({ok:true,data:{move:OLD,created:false}});expect(proof.requests).toHaveLength(1);});
it('explicit read403 refuses before any POST',async()=>{const result=await createMove(scenario({code:'42501',message:'Synthetic move read refused'},{readStatus:403}),INPUT);proof.result=result;expect(result).toMatchObject({ok:false,code:'db'});expect(proof.requests).toHaveLength(1);expect(activity).toHaveLength(0);});
it('explicit POST403 refuses without success activity',async()=>{const result=await createMove(scenario([],{postStatus:403}),INPUT);proof.result=result;expect(result).toMatchObject({ok:false,code:'db'});expect(proof.requests.map((r:any)=>r.method)).toEqual(['GET','POST']);expect(activity).toHaveLength(0);});
it('invalid explicit date after a healthy empty read refuses without POST',async()=>{const result=await createMove(scenario([]),{...INPUT,moveDate:'2026-02-30'});proof.result=result;expect(result).toMatchObject({ok:false,code:'invalid_input'});expect(proof.requests).toHaveLength(1);expect(activity).toHaveLength(0);});

// Additional wire bodies must refuse before a create; array entries stay opaque.
for(const [name,body] of [['zero',0],['true',true],['empty string',''],['serialized array string','[]'],['missing index array-like',{length:1}],['null index array-like',{0:null,length:1}],['wrapped collection',{data:[]}],['primitive index array-like',{0:7,length:1}]] as const){it('additional malformed open-move '+name+' returns the load refusal without POST',async()=>{const result=await createMove(scenario(body),INPUT);proof.result=result;expect(result).toEqual({ok:false,error:'Could not load the move.',code:'db'});expect(proof.requests.map((r:any)=>r.method)).toEqual(['GET']);expect(activity).toHaveLength(0);});}
it('truthy primitive first array entry preserves opaque prior-move behavior',async()=>{const result=await createMove(scenario([7,null,OLD]),INPUT);proof.result=result;expect(result).toEqual({ok:true,data:{move:7,created:false}});expect(proof.requests.map((r:any)=>r.method)).toEqual(['GET']);expect(activity).toHaveLength(0);});
it('null first array entry preserves fallback without scanning later entries',async()=>{const result=await createMove(scenario([null,OLD]),INPUT);proof.result=result;expect(result).toMatchObject({ok:true,data:{created:true}});expect(proof.requests.map((r:any)=>r.method)).toEqual(['GET','POST']);expect(activity).toHaveLength(1);});
it('false first array entry preserves existing create decision',async()=>{const result=await createMove(scenario([false,OLD]),INPUT);proof.result=result;expect(result).toMatchObject({ok:true,data:{created:true}});expect(proof.requests.map((r:any)=>r.method)).toEqual(['GET','POST']);expect(activity).toHaveLength(1);});
