import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';import {createClient} from '@supabase/supabase-js';import {afterAll,afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const root=process.env.BUBALY_NOTES_CAS_SOURCE_ROOT??process.cwd();
const sources=Object.fromEntries(Object.entries({notes:'lib/services/notes/index.ts',types:'lib/services/types.ts',errors:'lib/supabase/errors.ts'}).map(([k,p])=>[k,ts.transpileModule(fs.readFileSync(path.join(root,p),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText]));
const initial={id:'note-A',family_id:'family-A',title:'Synthetic title',body:'Neutral ordinary body',is_pinned:false,created_by:'synthetic-user-A'};
const traces:any[]=[];let trace:any;
beforeEach(()=>{trace={name:expect.getState().currentTestName,requests:[],readSnapshots:[],patches:[],activity:[],transportErrors:[],forbidden:[],logs:[],settled:0};vi.spyOn(console,'error').mockImplementation((...args)=>trace.logs.push(args));});
afterEach(()=>{traces.push(trace);expect(trace.forbidden).toEqual([]);expect(trace.transportErrors).toEqual([]);expect(trace.requests.length).toBeLessThanOrEqual(4);expect(trace.settled).toBe(trace.requests.length);expect(trace.logs.every((a:any[])=>['[service:notes] read failed','[service:notes] update failed'].includes(a[0]))).toBe(true);vi.restoreAllMocks();});
afterAll(()=>{if(process.env.BUBALY_NOTES_PARTIAL_TRACE)fs.writeFileSync(process.env.BUBALY_NOTES_PARTIAL_TRACE,JSON.stringify(traces,null,2)+'\n');});
function fixture(order?:'title-first'|'body-first',readError=false,beforeFirstPatch?:Partial<typeof initial>){
 let row={...initial},reads=0,firstPatch=true;let ready!:()=>void,firstDone!:()=>void;const readGate=new Promise<void>(r=>ready=r),writeGate=new Promise<void>(r=>firstDone=r);
 const deny=(why:string):never=>{trace.forbidden.push(why);throw Error('Outside modeled note update: '+why);};
 const transport:typeof fetch=async(input,init)=>{try{const url=new URL(String(input)),method=init?.method??'GET',headers=new Headers(init?.headers);if(url.origin!=='https://notes-partial.invalid'||url.pathname!=='/rest/v1/notes'||!['GET','PATCH'].includes(method)||url.searchParams.get('id')!=='eq.note-A'||url.searchParams.get('family_id')!=='eq.family-A'||url.searchParams.get('select')!=='*'||trace.requests.length>=4)deny('unexpected SDK request');trace.requests.push({method,path:url.pathname,query:url.search,prefer:headers.get('prefer')});
  if(method==='GET'){const snapshot={...row};trace.readSnapshots.push(snapshot);reads++;if(order){if(reads===2)ready();await readGate;}trace.settled++;return new Response(JSON.stringify(readError?{code:'42501',message:'Synthetic refused'}:[snapshot]),{status:readError?403:200,headers:{'content-type':'application/json'}});}
  if(readError)deny('PATCH after refused GET');const patch=JSON.parse(String(init?.body));if(Object.keys(patch).some(k=>!['title','body','is_pinned'].includes(k)))deny('unexpected patch column');
  const predicates=[...url.searchParams].filter(([key])=>!['select','id','family_id'].includes(key));for(const [key,value]of predicates)if(!['title','body'].includes(key)||!(value.startsWith('eq.')||(key==='title'&&value==='is.null')))deny('unexpected conditional predicate');
  let preferred=true;if(order){const isTitle=Object.hasOwn(patch,'title');preferred=order==='title-first'?isTitle:!isTitle;if(!preferred)await writeGate;}
  if(firstPatch){firstPatch=false;if(beforeFirstPatch){row={...row,...beforeFirstPatch};trace.interleaving={...beforeFirstPatch};}}
  // Evaluate modeled SQL-style predicates at the atomic PATCH step AFTER the held interleaving barrier.
  const matches=predicates.every(([key,value])=>value==='is.null'?row[key as 'title'|'body']===null:row[key as 'title'|'body']!==null&&row[key as 'title'|'body']===value.slice(3));
  if(matches)row={...row,...patch};trace.patches.push({patch,predicates,matched:matches,result:matches?{...row}:null});if(order&&preferred)firstDone();trace.settled++;
  return new Response(JSON.stringify(matches?[row]:[]),{status:200,headers:{'content-type':'application/json'}});
 }catch(error){trace.transportErrors.push(String(error));throw error;}};
 const db=createClient('https://notes-partial.invalid','synthetic-public-key',{accessToken:async()=>null,global:{fetch:transport},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),scope={db,familyId:'family-A',userId:'synthetic-user-A',memberId:'synthetic-member-A',role:'parent',actorKind:'member',tz:'UTC'},modules:Record<string,any>={};
 function load(id:string):any{if(id==='server-only')return{};if(id==='../activity')return{recordActivitySafely:async(_scope:any,activity:any)=>trace.activity.push(activity)};const key=id==='../types'?'types':id==='@/lib/supabase/errors'?'errors':id;if(!(key in sources))return deny('unapproved import '+id);if(modules[key])return modules[key].exports;const entry=modules[key]={exports:{}};new Function('require','module','exports',sources[key])(load,entry,entry.exports);return entry.exports;}
 return{call:(input:any)=>load('notes').updateNote(scope,'note-A',input),row:()=>({...row}),raw:db};
}
describe('original notes partial edit modeled interleaving',()=>{
 for(const order of ['title-first','body-first'] as const)it('two snapshot edits cannot both confirm a finally empty note: '+order,async()=>{const f=fixture(order);const results=await Promise.all([f.call({title:null}),f.call({body:''})]);trace.final=f.row();trace.results=results;expect(trace.readSnapshots).toEqual([initial,initial]);expect(trace.requests.map((r:any)=>r.method)).toEqual(['GET','GET','PATCH','PATCH']);expect(trace.patches.map((p:any)=>Object.keys(p.patch)[0])).toEqual(order==='title-first'?['title','body']:['body','title']);expect.soft(results.some(r=>!r.ok)).toBe(true);expect.soft(Boolean(f.row().title?.trim()||f.row().body.trim())).toBe(true);});
 it('sequential title clear then body clear refuses the second edit',async()=>{const f=fixture();expect(await f.call({title:null})).toMatchObject({ok:true});expect(await f.call({body:''})).toMatchObject({ok:false,code:'invalid_input'});expect(f.row()).toMatchObject({title:null,body:initial.body});expect(trace.activity).toHaveLength(1);expect(trace.requests.map((r:any)=>r.method)).toEqual(['GET','PATCH','GET']);});
 it('sequential body clear then title clear refuses the second edit',async()=>{const f=fixture();expect(await f.call({body:''})).toMatchObject({ok:true});expect(await f.call({title:null})).toMatchObject({ok:false,code:'invalid_input'});expect(f.row()).toMatchObject({title:initial.title,body:''});expect(trace.activity).toHaveLength(1);expect(trace.requests.map((r:any)=>r.method)).toEqual(['GET','PATCH','GET']);});
 it('same request clearing both fields refuses before PATCH',async()=>{const f=fixture();expect(await f.call({title:null,body:''})).toMatchObject({ok:false,code:'invalid_input'});expect(f.row()).toEqual(initial);expect(trace.requests.map((r:any)=>r.method)).toEqual(['GET']);expect(trace.activity).toEqual([]);});
 it('healthy title edit preserves body and emits one inert activity',async()=>{const f=fixture();expect(await f.call({title:'Revised ordinary title'})).toMatchObject({ok:true,data:{title:'Revised ordinary title',body:initial.body}});expect(trace.patches).toHaveLength(1);expect(trace.activity).toHaveLength(1);});
 it('healthy body edit preserves title and emits one inert activity',async()=>{const f=fixture();expect(await f.call({body:'Revised neutral text'})).toMatchObject({ok:true,data:{title:initial.title,body:'Revised neutral text'}});expect(trace.patches).toHaveLength(1);expect(trace.activity).toHaveLength(1);});
 it('empty edit refuses after read with no PATCH or activity',async()=>{const f=fixture();expect(await f.call({})).toMatchObject({ok:false,code:'invalid_input'});expect(f.row()).toEqual(initial);expect(trace.requests.map((r:any)=>r.method)).toEqual(['GET']);expect(trace.activity).toEqual([]);});
 it('read403 refuses before any PATCH or activity',async()=>{const f=fixture(undefined,true);expect(await f.call({title:null})).toMatchObject({ok:false,code:'db'});expect(trace.requests.map((r:any)=>r.method)).toEqual(['GET']);expect(trace.activity).toEqual([]);});
});
describe('modeled conditional PATCH filter guards',()=>{
 it('matches exact title/body once then refuses stale predicates without changing the other field',async()=>{const f=fixture();const first=await f.raw.from('notes').update({title:null}).eq('id','note-A').eq('family_id','family-A').eq('title',initial.title).eq('body',initial.body).select('*').maybeSingle();expect(first.error).toBeNull();expect(first.data).toMatchObject({title:null,body:initial.body});const stale=await f.raw.from('notes').update({body:''}).eq('id','note-A').eq('family_id','family-A').eq('title',initial.title).eq('body',initial.body).select('*').maybeSingle();expect(stale.data).toBeNull();expect(stale.error).toBeNull();expect(f.row()).toMatchObject({title:null,body:initial.body});expect(trace.patches.map((p:any)=>p.matched)).toEqual([true,false]);expect(trace.activity).toEqual([]);});
 it('matches an explicit nullable-title predicate at the atomic PATCH step',async()=>{const f=fixture();expect(await f.call({title:null})).toMatchObject({ok:true});const result=await f.raw.from('notes').update({body:'Revised neutral body'}).eq('id','note-A').eq('family_id','family-A').is('title',null).eq('body',initial.body).select('*').maybeSingle();expect(result.error).toBeNull();expect(result.data).toMatchObject({title:null,body:'Revised neutral body'});expect(trace.patches[1].predicates).toContainEqual(['title','is.null']);expect(trace.patches[1].matched).toBe(true);expect(trace.activity).toHaveLength(1);});
 it('a mismatched nullable-title predicate returns no row and leaves storage unchanged',async()=>{const f=fixture();const result=await f.raw.from('notes').update({body:''}).eq('id','note-A').eq('family_id','family-A').is('title',null).eq('body',initial.body).select('*').maybeSingle();expect(result.data).toBeNull();expect(result.error).toBeNull();expect(f.row()).toEqual(initial);expect(trace.patches[0].matched).toBe(false);expect(trace.activity).toEqual([]);});
});

describe('notes captured-content conditional write controls',()=>{
 for(const order of ['title-first','body-first'] as const)it('only the current nonempty content wins with one refused clear and one activity: '+order,async()=>{const f=fixture(order);const results=await Promise.all([f.call({title:null}),f.call({body:''})]);expect(results.filter(r=>r.ok)).toHaveLength(1);expect(results.filter(r=>!r.ok)).toHaveLength(1);expect(results.find(r=>!r.ok)).toMatchObject({ok:false,code:'db',error:expect.any(String)});expect(trace.activity).toHaveLength(1);expect(trace.patches.map((p:any)=>p.matched)).toEqual([true,false]);expect(Boolean(f.row().title?.trim()||f.row().body.trim())).toBe(true);});
 it('a service content edit can follow a captured nullable title',async()=>{const f=fixture();expect(await f.call({title:null})).toMatchObject({ok:true});expect(await f.call({body:'Revised neutral body'})).toMatchObject({ok:true,data:{title:null,body:'Revised neutral body'}});expect(trace.activity).toHaveLength(2);});
 for(const order of ['title-first','body-first'] as const)it('a pin-only edit and a content edit both complete without a false content conflict: '+order,async()=>{const f=fixture(order);const results=await Promise.all([f.call({title:'Revised ordinary title'}),f.call({pinned:true})]);expect(results.every(r=>r.ok)).toBe(true);expect(f.row()).toMatchObject({title:'Revised ordinary title',body:initial.body,is_pinned:true});expect(trace.activity).toHaveLength(2);expect(trace.patches).toHaveLength(2);});
 it('a refused stale content write can be retried against the latest nonempty content',async()=>{const f=fixture(undefined,false,{body:'Concurrent neutral body'});expect(await f.call({title:null})).toMatchObject({ok:false,code:'db'});expect(trace.activity).toEqual([]);expect(f.row()).toMatchObject({title:initial.title,body:'Concurrent neutral body'});expect(await f.call({title:null})).toMatchObject({ok:true,data:{title:null,body:'Concurrent neutral body'}});expect(trace.patches.map((p:any)=>p.matched)).toEqual([false,true]);expect(trace.activity).toHaveLength(1);});
 it('a pin-only write keeps a concurrently changed body without requiring old content',async()=>{const f=fixture(undefined,false,{body:'Concurrent neutral body'});expect(await f.call({pinned:true})).toMatchObject({ok:true,data:{title:initial.title,body:'Concurrent neutral body',is_pinned:true}});expect(trace.activity).toHaveLength(1);expect(trace.patches[0].predicates).toEqual([]);});
});
