import { afterEach, expect, it, vi } from 'vitest';
import { appendFileSync } from 'node:fs';
import { createClient } from '@supabase/supabase-js';
import { listDue } from '@/lib/services/reminders';
vi.mock('@/lib/services/activity', () => ({ recordActivitySafely: (...args: unknown[]) => { (globalThis as any).__dueActivity?.push(args); throw Error('Unadmitted activity invocation'); } }));
vi.mock('@/lib/reminders/details', () => ({ nextRemindAt: () => { throw Error('Unadmitted reminder details invocation'); } }));

const FAMILY='a1111111-1111-4111-8111-111111111111',MEMBER='b2222222-2222-4222-8222-222222222222',NOW='2026-10-10T15:00:00.000Z';
const active={id:'active-1',family_id:FAMILY,status:'active',remind_at:NOW};let proof:any;
afterEach(()=>{expect(proof.forbidden).toEqual([]);expect(proof.transportErrors).toEqual([]);expect(proof.active).toBe(0);expect(proof.requests.length).toBeLessThanOrEqual(1);expect(proof.actualSdkReplies.length).toBe(proof.requests.length);expect(proof.activity).toEqual([]);for(const request of proof.requests){const q=new URLSearchParams(request.query);expect(request.method).toBe('GET');expect(request.table).toBe('family_reminders');expect([...q.keys()].sort()).toEqual(['family_id','limit','order','remind_at','remind_at','select','status',...(proof.input.memberId?['member_id']:[])].sort());expect(q.get('family_id')).toBe('eq.'+FAMILY);expect(q.get('status')).toBe('in.(active,snoozed)');expect(q.get('select')).toBe('*');expect(q.getAll('remind_at')).toEqual(['not.is.null','lte.'+proof.expectedHorizon]);expect(q.get('order')).toBe('remind_at.asc');expect(q.get('limit')).toBe(String(Math.min(Math.max(proof.input.limit??100,1),500)));if(proof.input.memberId)expect(q.get('member_id')).toBe('eq.'+proof.input.memberId);expect(request.payload).toBeNull();}if(process.env.BUBALY_REMINDER_DUE_RECEIPTS)appendFileSync(process.env.BUBALY_REMINDER_DUE_RECEIPTS,JSON.stringify({...proof,test:expect.getState().currentTestName})+String.fromCharCode(10));});
async function run(body:any=[],options:any={}){const input=options.input??{};const before=input.before?Date.parse(input.before):Date.parse(NOW)+(input.withinMinutes??0)*60000;proof={input,expectedHorizon:Number.isFinite(before)?new Date(before).toISOString():null,requests:[],rawResponses:[],actualSdkReplies:[],declaredAdapters:[],activity:[],forbidden:[],transportErrors:[],active:0,status:options.status??200};(globalThis as any).__dueActivity=proof.activity;
const db=createClient('https://reminder-due-collection.invalid','synthetic-key',{accessToken:async()=>null,auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},global:{fetch:async(url:any,init:any={})=>{proof.active++;try{const u=new URL(String(url));const method=init.method??'GET';if(u.origin!=='https://reminder-due-collection.invalid'||u.pathname!=='/rest/v1/family_reminders'||method!=='GET'||proof.requests.length>=1){proof.forbidden.push(String(url));throw Error('Forbidden finite transport');}const headers=new Headers(init.headers);proof.requests.push({method,table:'family_reminders',query:u.search,accept:headers.get('accept'),prefer:headers.get('prefer'),payload:init.body?JSON.parse(String(init.body)):null});proof.rawResponses.push({status:proof.status,body:proof.status===204?null:body});return new Response(proof.status===204?null:JSON.stringify(body),{status:proof.status,headers:{'content-type':'application/json'}});}catch(error){proof.transportErrors.push(error instanceof Error?error.message:String(error));throw error;}finally{proof.active--;}}}});
function observe(builder:any):any{return new Proxy(builder,{get(target,key){if(key==='then')return(fulfilled:any,rejected:any)=>target.then((reply:any)=>{proof.actualSdkReplies.push({status:reply.status,data:reply.data,dataUndefined:reply.data===undefined,error:reply.error});let next=reply;if(options.adapter==='undefined'){next={...reply,data:undefined};proof.declaredAdapters.push({kind:'post-await data undefined'});}if(options.adapter==='error'){next={...reply,error:{code:'42501',message:'Declared synthetic read refusal'}};proof.declaredAdapters.push({kind:'post-await data plus explicit error'});}return next;}).then(fulfilled,rejected);const value=Reflect.get(target,key,target);if(typeof value!=='function')return value;return(...args:any[])=>{const next=value.apply(target,args);return next&&typeof next==='object'?observe(next):next;};}});}
const scope:any={db:{from:(table:string)=>{if(table!=='family_reminders'){proof.forbidden.push(table);throw Error('Forbidden builder');}return observe(db.from(table));}},familyId:FAMILY,userId:'synthetic-user',memberId:MEMBER,role:'parent',actorKind:'member',tz:'UTC',now:new Date(NOW)};try{const result=await listDue(scope,input);proof.result=result;return result;}catch(error){proof.serviceThrown=error instanceof Error?error.message:String(error);proof.result={thrown:proof.serviceThrown};return proof.result;}}
// ORIGINAL CASES BEGIN
it('successful plain object receipt returns structured read refusal',async()=>{expect(await run({})).toMatchObject({ok:false,code:'db'});expect(proof.requests).toHaveLength(1);});
it('successful empty array-like object receipt returns structured read refusal',async()=>{expect(await run({length:0})).toMatchObject({ok:false,code:'db'});expect(proof.requests).toHaveLength(1);});
it('successful populated array-like object receipt returns structured read refusal',async()=>{expect(await run({length:1,0:active})).toMatchObject({ok:false,code:'db'});expect(proof.requests).toHaveLength(1);});
it('successful empty string receipt returns structured read refusal',async()=>{expect(await run('')).toMatchObject({ok:false,code:'db'});expect(proof.requests).toHaveLength(1);});
it('successful nonempty string receipt returns structured read refusal',async()=>{expect(await run('malformed')).toMatchObject({ok:false,code:'db'});expect(proof.requests).toHaveLength(1);});
it('successful zero receipt returns structured read refusal',async()=>{expect(await run(0)).toMatchObject({ok:false,code:'db'});expect(proof.requests).toHaveLength(1);});
it('successful finite nonzero number receipt returns structured read refusal',async()=>{expect(await run(7)).toMatchObject({ok:false,code:'db'});expect(proof.requests).toHaveLength(1);});
it('successful false boolean receipt returns structured read refusal',async()=>{expect(await run(false)).toMatchObject({ok:false,code:'db'});expect(proof.requests).toHaveLength(1);});
it('successful true boolean receipt returns structured read refusal',async()=>{expect(await run(true)).toMatchObject({ok:false,code:'db'});expect(proof.requests).toHaveLength(1);});
it('successful object with nonfunction filter receipt returns structured read refusal',async()=>{expect(await run({filter:"opaque"})).toMatchObject({ok:false,code:'db'});expect(proof.requests).toHaveLength(1);});
it('healthy empty array preserves complete empty result and minimum limit',async()=>{expect(await run([],{input:{limit:0}})).toEqual({ok:true,data:[]});expect(proof.requests).toHaveLength(1);});
it('healthy active array preserves entries and provided-now default horizon',async()=>{expect(await run([active])).toEqual({ok:true,data:[active]});expect(proof.requests).toHaveLength(1);});
it('snooze filtering preserves elapsed missing and invalid-until policy',async()=>{const elapsed={...active,id:'elapsed',status:'snoozed',snoozed_until:'2026-10-10T14:59:00Z'},future={...active,id:'future',status:'snoozed',snoozed_until:'2026-10-10T15:01:00Z'},missing={...active,id:'missing',status:'snoozed',snoozed_until:null},invalid={...active,id:'invalid',status:'snoozed',snoozed_until:'bad'};expect(await run([active,future,elapsed,missing,invalid])).toEqual({ok:true,data:[active,elapsed,missing,invalid]});});
it('nonnull opaque array entries preserve existing collection-only policy',async()=>{const rows=[17,false,'opaque',{id:'opaque-object'}];expect(await run(rows)).toEqual({ok:true,data:rows});});
it('HTTP200 null receipt preserves intentional empty result',async()=>{expect(await run(null)).toEqual({ok:true,data:[]});});
it('HTTP204 receipt preserves intentional empty result',async()=>{expect(await run(null,{status:204})).toEqual({ok:true,data:[]});});
it('declared post-await undefined data preserves nullish empty policy',async()=>{expect(await run([],{adapter:'undefined'})).toEqual({ok:true,data:[]});expect(proof.actualSdkReplies[0].data).toEqual([]);expect(proof.declaredAdapters).toEqual([{kind:'post-await data undefined'}]);});
it('HTTP403 error preserves structured database refusal before filtering',async()=>{expect(await run({code:'42501',message:'Synthetic read denied'},{status:403})).toMatchObject({ok:false,code:'db'});});
it('declared data-plus-error adapter preserves explicit error precedence',async()=>{expect(await run([active],{adapter:'error'})).toMatchObject({ok:false,code:'db'});expect(proof.actualSdkReplies[0].error).toBeNull();expect(proof.actualSdkReplies[0].data).toEqual([active]);});
it('invalid horizon refuses before any SDK request',async()=>{expect(await run([],{input:{before:'invalid'}})).toMatchObject({ok:false,code:'invalid_input'});expect(proof.requests).toEqual([]);});
it('explicit offset horizon and member preserve exact family-scoped GET filters',async()=>{expect(await run([active],{input:{before:'2026-10-10T11:00:00-04:00',memberId:MEMBER,limit:12}})).toEqual({ok:true,data:[active]});expect(proof.expectedHorizon).toBe(NOW);});
it('within-minutes horizon and upper limit preserve bounded query semantics',async()=>{expect(await run([],{input:{withinMinutes:5,limit:501}})).toEqual({ok:true,data:[]});expect(proof.expectedHorizon).toBe('2026-10-10T15:05:00.000Z');});
// ORIGINAL CASES END
