import type { SupabaseBrowser } from '@/lib/supabase/types';

export const FEEDBACK_ATTACHMENTS_BUCKET = 'feedback-attachments';
export const FEEDBACK_ATTACHMENT_MAX_BYTES = 10 * 1024 * 1024;

const PUBLIC_PATH = `/storage/v1/object/public/${FEEDBACK_ATTACHMENTS_BUCKET}/`;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/** Return a deletable path only for a URL generated by this project's bucket. */
export function feedbackAttachmentPathFromUrl(value: string, expectedOrigin?: string): string | null {
  try {
    const url = new URL(value.trim());
    if (expectedOrigin && url.origin !== new URL(expectedOrigin).origin) return null;
    if (!url.pathname.startsWith(PUBLIC_PATH)) return null;

    const path = decodeURIComponent(url.pathname.slice(PUBLIC_PATH.length));
    const parts = path.split('/');
    if (parts.length < 2 || !UUID.test(parts[0]) || parts.some((part) => !part || part === '.' || part === '..')) {
      return null;
    }
    return path;
  } catch {
    return null;
  }
}

/**
 * The storage path for a stored attachment value, whether it is a bare path or
 * one of the public URLs this bucket used to hand out.
 *
 * The bucket is private as of 0325, so `getPublicUrl` no longer produces
 * anything that resolves and new uploads record the path itself. Rows written
 * before that still hold the full `/storage/v1/object/public/...` URL, and they
 * are not rewritten: this reads either, and the admin console signs whatever
 * comes back. A value that is neither — an external link, a malformed string,
 * a path that escapes its folder — returns null rather than something to sign.
 */
export function feedbackAttachmentPath(value: string, expectedOrigin?: string): string | null {
  const raw = value.trim();
  if (!raw) return null;
  if (raw.includes('://')) return feedbackAttachmentPathFromUrl(raw, expectedOrigin);
  const parts = raw.split('/');
  if (parts.length < 2 || !UUID.test(parts[0])) return null;
  if (parts.some((part) => !part || part === '.' || part === '..')) return null;
  return raw;
}

export async function removeFeedbackAttachmentPath(
  supabase: SupabaseBrowser,
  path: string,
): Promise<{ error: string | null }> {
  const { error } = await supabase.storage.from(FEEDBACK_ATTACHMENTS_BUCKET).remove([path]);
  return { error: error?.message ?? null };
}
