// Pure: which feedback-attachment URLs are this project's own. Kept apart from
// feedback-attachments.ts so the no-Supabase feedback engine (lib/feedback/board.ts)
// can use it without pulling in client helpers.

export const FEEDBACK_ATTACHMENTS_BUCKET = 'feedback-attachments';

const PUBLIC_PATH = `/storage/v1/object/public/${FEEDBACK_ATTACHMENTS_BUCKET}/`;
const SIGNED_PATH = `/storage/v1/object/sign/${FEEDBACK_ATTACHMENTS_BUCKET}/`;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/** `path` if it names an object in a user's folder: a uuid folder, no empty or dot segment. */
function objectPath(path: string): string | null {
  const parts = path.split('/');
  if (parts.length < 2 || !UUID.test(parts[0]) || parts.some((part) => !part || part === '.' || part === '..')) {
    return null;
  }
  return path;
}

/** The object path under `prefix` of this project's bucket. */
function objectPathUnder(url: URL, prefix: string, expectedOrigin?: string): string | null {
  if (expectedOrigin && url.origin !== new URL(expectedOrigin).origin) return null;
  if (!url.pathname.startsWith(prefix)) return null;
  return objectPath(decodeURIComponent(url.pathname.slice(prefix.length)));
}

/** Return a deletable path only for a URL generated by this project's bucket. */
export function feedbackAttachmentPathFromUrl(value: string, expectedOrigin?: string): string | null {
  try {
    return objectPathUnder(new URL(value.trim()), PUBLIC_PATH, expectedOrigin);
  } catch {
    return null;
  }
}

/**
 * The object path a STORED attachment value names, whichever form it takes:
 * a bare `<user>/<object>` path, which is what an upload records as of 0450
 * (the bucket is private, so a public URL no longer resolves), or this
 * project's public URL, which rows written before that still hold. Anything
 * else — an external link, a malformed string, a path that escapes its
 * folder — is null.
 */
export function feedbackAttachmentObjectPath(value: string, expectedOrigin?: string): string | null {
  const raw = value.trim();
  if (!raw) return null;
  if (raw.includes('://')) return feedbackAttachmentPathFromUrl(raw, expectedOrigin);
  return objectPath(raw);
}

/**
 * The object path of a SIGNED URL for this project's bucket, or null: what the
 * super-admin console is handed. The bucket is private (F-E05), so
 * lib/storage/feedback-attachment-signing.ts replaces each stored value with a
 * short-lived /object/sign/ URL before the page renders, and the console's
 * re-check has to accept that form: checking for the stored /object/public/
 * form refused every screenshot. Anything else is still not fetched: another
 * bucket, another origin, a traversal, a URL without its token.
 */
export function feedbackAttachmentPathFromSignedUrl(value: string, expectedOrigin?: string): string | null {
  try {
    const url = new URL(value.trim());
    if (!url.searchParams.get('token')) return null;
    return objectPathUnder(url, SIGNED_PATH, expectedOrigin);
  } catch {
    return null;
  }
}
