import type { SupabaseBrowser } from '@/lib/supabase/types';

export const MARKETPLACE_PHOTOS_BUCKET = 'marketplace-photos';
export const MARKETPLACE_PHOTO_MAX_BYTES = 10 * 1024 * 1024;

const PUBLIC_PATH = `/storage/v1/object/public/${MARKETPLACE_PHOTOS_BUCKET}/`;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/** Return a deletable path only for a URL generated by this project's bucket. */
export function marketplacePhotoPathFromUrl(value: string, expectedOrigin?: string): string | null {
  try {
    const url = new URL(value.trim());
    if (expectedOrigin && url.origin !== new URL(expectedOrigin).origin) return null;
    if (!url.pathname.startsWith(PUBLIC_PATH)) return null;

    const path = decodeURIComponent(url.pathname.slice(PUBLIC_PATH.length));
    const parts = path.split('/');
    if (parts.length < 2 || !UUID.test(parts[0]) || parts.some((part) => !part || part === '.' || part === '..')) {
      return null;
    }
    return path;
  } catch {
    return null;
  }
}

export async function removeMarketplacePhotoPath(
  supabase: SupabaseBrowser,
  path: string,
): Promise<{ error: string | null }> {
  const { error } = await supabase.storage.from(MARKETPLACE_PHOTOS_BUCKET).remove([path]);
  return { error: error?.message ?? null };
}

export async function removeMarketplacePhotoUrl(
  supabase: SupabaseBrowser,
  value: string,
): Promise<{ removed: boolean; error: string | null }> {
  const path = marketplacePhotoPathFromUrl(value, process.env.NEXT_PUBLIC_SUPABASE_URL);
  if (!path) return { removed: false, error: null };
  const result = await removeMarketplacePhotoPath(supabase, path);
  return { removed: !result.error, error: result.error };
}
