import type { MetadataRoute } from 'next';

/** PWA manifest — enables "Add to Home Screen" + installable app behavior, and is
 *  the web asset source for the Capacitor native shells (iOS/iPadOS/Android).
 *  Icons are real PNGs generated by scripts/generate-icons.mjs. */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Bubaly — Family Operating System',
    short_name: 'Bubaly',
    description: 'The AI operating system for family life — less managing life, more living it.',
    start_url: '/dashboard',
    scope: '/',
    display: 'standalone',
    // 'any', not 'portrait': tablets rotate (M-014 landscape safe-area work) and
    // the /display kitchen-wall kiosk is designed for landscape tablets — a
    // portrait lock would freeze the installed PWA sideways on both (M-025).
    orientation: 'any',
    background_color: '#090c14',
    theme_color: '#090c14',
    categories: ['productivity', 'lifestyle', 'utilities'],
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icons/maskable-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: '/icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
    shortcuts: [
      { name: 'Daily Briefing', short_name: 'Briefing', url: '/dashboard/briefing' },
      { name: 'Calendar', short_name: 'Calendar', url: '/dashboard/calendar' },
      { name: 'Assistant', short_name: 'Assistant', url: '/dashboard/assistant' },
      { name: 'Grocery', short_name: 'Grocery', url: '/dashboard/grocery' },
    ],
  };
}
