import type { MetadataRoute } from 'next';

/** PWA manifest — enables "Add to Home Screen" + installable app behavior, and is
 *  the web asset source for the Capacitor native shells (iOS/iPadOS/Android).
 *  Icons are real PNGs generated by scripts/generate-icons.mjs. */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'FamilyOS — Family Operating System',
    short_name: 'FamilyOS',
    description: 'An AI chief of staff for busy households.',
    start_url: '/dashboard',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#090c14',
    theme_color: '#090c14',
    categories: ['productivity', 'lifestyle', 'utilities'],
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icons/maskable-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: '/icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      { src: '/icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
    ],
    shortcuts: [
      { name: 'Daily Briefing', short_name: 'Briefing', url: '/dashboard/briefing' },
      { name: 'Calendar', short_name: 'Calendar', url: '/dashboard/calendar' },
      { name: 'Assistant', short_name: 'Assistant', url: '/dashboard/assistant' },
      { name: 'Grocery', short_name: 'Grocery', url: '/dashboard/grocery' },
    ],
  };
}
