// components/vacations/trip-labels.ts — the trip tabs' form labels in the reader's language.
//
// Each tab declares its fields as English FieldDef data; TripCrudSection words
// every label, option and add-button through this map (audit C1-S9-133). A
// label missing here still reads as its English rather than a raw key.
export const TRIP_LABEL_KEYS: Record<string, string> = {
  "Accessibility needs": 'tripLabel.accessibilityNeeds',
  "Activity": 'tripLabel.activity',
  "Add activity": 'tripLabel.addActivity',
  "Add contact": 'tripLabel.addContact',
  "Add document": 'tripLabel.addDocument',
  "Add flight": 'tripLabel.addFlight',
  "Add lodging": 'tripLabel.addLodging',
  "Add medical info": 'tripLabel.addMedicalInfo',
  "Add reservation": 'tripLabel.addReservation',
  "Add transport": 'tripLabel.addTransport',
  "Add traveler": 'tripLabel.addTraveler',
  "Address": 'tripLabel.address',
  "Adult": 'tripLabel.adult',
  "Airline": 'tripLabel.airline',
  "Allergies": 'tripLabel.allergies',
  "Amount ($)": 'tripLabel.amountUsd',
  "Arrives": 'tripLabel.arrives',
  "Belongs to": 'tripLabel.belongsTo',
  "Blood type": 'tripLabel.bloodType',
  "Booked": 'tripLabel.booked',
  "Booked & confirmed": 'tripLabel.bookedAndConfirmed',
  "Caregiver": 'tripLabel.caregiver',
  "Category": 'tripLabel.category',
  "Check-in": 'tripLabel.checkIn',
  "Check-out": 'tripLabel.checkOut',
  "Child": 'tripLabel.child',
  "Conditions": 'tripLabel.conditions',
  "Confirmation": 'tripLabel.confirmation',
  "Cost ($)": 'tripLabel.costUsd',
  "Date": 'tripLabel.date',
  "Departs": 'tripLabel.departs',
  "Description": 'tripLabel.description',
  "Dietary restrictions": 'tripLabel.dietaryRestrictions',
  "Distance (mi)": 'tripLabel.distanceMi',
  "Doctor": 'tripLabel.doctor',
  "Duration (min)": 'tripLabel.durationMin',
  "Email": 'tripLabel.email',
  "Embassy": 'tripLabel.embassy',
  "Emergency contact": 'tripLabel.emergencyContact',
  "Expires": 'tripLabel.expires',
  "Family": 'tripLabel.family',
  "Family member": 'tripLabel.familyMember',
  "Family-friendly": 'tripLabel.familyFriendly',
  "File link": 'tripLabel.fileLink',
  "Flight #": 'tripLabel.flightNumber',
  "From": 'tripLabel.from',
  "From (airport)": 'tripLabel.fromAirport',
  "Fuel est. ($)": 'tripLabel.fuelEstUsd',
  "Gate": 'tripLabel.gate',
  "Grandparent": 'tripLabel.grandparent',
  "Insurance": 'tripLabel.insurance',
  "Insurance #": 'tripLabel.insuranceNumber',
  "Insurance provider": 'tripLabel.insuranceProvider',
  "Issued": 'tripLabel.issued',
  "Link": 'tripLabel.link',
  "Local emergency": 'tripLabel.localEmergency',
  "Location": 'tripLabel.location',
  "Log expense": 'tripLabel.logExpense',
  "Medical notes": 'tripLabel.medicalNotes',
  "Medications": 'tripLabel.medications',
  "Name": 'tripLabel.name',
  "Nightly ($)": 'tripLabel.nightlyUsd',
  "Notes": 'tripLabel.notes',
  "Number": 'tripLabel.number',
  "Other": 'tripLabel.other',
  "Paid by": 'tripLabel.paidBy',
  "Party size": 'tripLabel.partySize',
  "Phone": 'tripLabel.phone',
  "Physician": 'tripLabel.physician',
  "Physician phone": 'tripLabel.physicianPhone',
  "Preferences": 'tripLabel.preferences',
  "Provider": 'tripLabel.provider',
  "Relationship": 'tripLabel.relationship',
  "Reservation": 'tripLabel.reservation',
  "Role": 'tripLabel.role',
  "Seats": 'tripLabel.seats',
  "Terminal": 'tripLabel.terminal',
  "Title": 'tripLabel.title',
  "To": 'tripLabel.to',
  "To (airport)": 'tripLabel.toAirport',
  "Total ($)": 'tripLabel.totalUsd',
  "Type": 'tripLabel.type',
  "When": 'tripLabel.when',
  "or Guest name": 'tripLabel.orGuestName',
};

export function tripLabel(t: (key: string) => string, english: string): string {
  const key = TRIP_LABEL_KEYS[english];
  return key ? t(key) : english;
}
