-- Read-only catalog projection of SCHEMA_CHECKS at 190a93147.
-- Does not test REST exposure, row access, or production writes.
WITH expected(label, table_name, migration, columns) AS (VALUES ('workload_snapshots','workload_snapshots','0174_workload_snapshots.sql',''),
('independence_milestones','independence_milestones','0175_independence_milestones.sql',''),
('money_timeline_insights','money_timeline_insights','0168_money_timeline_insights.sql',''),
('paperwork_items','paperwork_items','0169_paperwork_items.sql',''),
('contact_interactions','contact_interactions','0170_contact_interactions.sql',''),
('crm_contact_profile','crm_contact_profile','0171_crm_contact_profile.sql',''),
('crm_lead_scores','crm_lead_scores','0172_crm_lead_scores.sql',''),
('marketplace_circles','marketplace_circles','0176_marketplace_circles.sql',''),
('resend_webhook_events','resend_webhook_events','0180_resend_webhook_dedup.sql',''),
('guardian_callback_events','guardian_callback_events','0181_guardian_callback_replay.sql',''),
('stripe_webhook_events.claim_columns','stripe_webhook_events','0189_reconcile_stripe_webhook_claims.sql','processing_started_at,claim_token'),
('wardrobe_items','wardrobe_items','0240_closet_outfits.sql',''),
('outfits','outfits','0240_closet_outfits.sql',''),
('outfit_logs','outfit_logs','0240_closet_outfits.sql',''),
('watchlist_titles','watchlist_titles','0241_family_watchlist.sql',''),
('watchlist_votes','watchlist_votes','0241_family_watchlist.sql',''),
('watch_sessions','watch_sessions','0241_family_watchlist.sql',''),
('home_locations','home_locations','0242_home_inventory.sql',''),
('inventory_items','inventory_items','0242_home_inventory.sql',''),
('inventory_moves','inventory_moves','0242_home_inventory.sql',''),
('sleep_logs','sleep_logs','0243_sleep_coach.sql',''),
('bedtime_routines','bedtime_routines','0243_sleep_coach.sql',''),
('sleep_checkins','sleep_checkins','0243_sleep_coach.sql',''),
('declutter_zones','declutter_zones','0244_declutter.sql',''),
('declutter_missions','declutter_missions','0244_declutter.sql',''),
('declutter_sessions','declutter_sessions','0244_declutter.sql',''),
('moves','moves','0245_move_planner.sql',''),
('move_tasks','move_tasks','0245_move_planner.sql',''),
('move_boxes','move_boxes','0245_move_planner.sql',''),
('home_projects','home_projects','0246_home_projects.sql',''),
('project_materials','project_materials','0246_home_projects.sql',''),
('project_quotes','project_quotes','0246_home_projects.sql',''),
('career_profiles','career_profiles','0247_career_hub.sql',''),
('job_applications','job_applications','0247_career_hub.sql',''),
('resume_versions','resume_versions','0247_career_hub.sql',''),
('language_goals','language_goals','0248_language_practice.sql',''),
('language_sessions','language_sessions','0248_language_practice.sql',''),
('vocab_cards','vocab_cards','0248_language_practice.sql',''),
('ai_requests','ai_requests','0250_ai_runtime_core.sql',''),
('ai_request_context','ai_request_context','0250_ai_runtime_core.sql',''),
('ai_plans','ai_plans','0250_ai_runtime_core.sql',''),
('ai_plan_steps','ai_plan_steps','0250_ai_runtime_core.sql',''),
('ai_run_events','ai_run_events','0250_ai_runtime_core.sql',''),
('ai_tool_calls','ai_tool_calls','0250_ai_runtime_core.sql',''),
('family_automation_runs.runtime_columns','family_automation_runs','0250_ai_runtime_core.sql','request_id,plan_id,requested_by_member_id,state,current_step_id,run_after,lease_owner,lease_expires_at,attempt,max_attempts,idempotency_key,cancel_requested_at,paused_at'),
('ai_conversations.runtime_columns','ai_conversations','0250_ai_runtime_core.sql','state,prompt_version'),
('ai_messages.runtime_columns','ai_messages','0250_ai_runtime_core.sql','structured_content,model,usage,request_id,sender_member_id'),
('approval_requests.runtime_columns','approval_requests','0251_ai_trust_hardening.sql','request_id,run_id,plan_step_id,plan_step_ids,consequences,evidence,edited_payload,payload_kind,reviewed_by,review_note'),
('ai_requests.runtime_columns','ai_requests','0255_ai_runtime_lockdown.sql','client_request_id'),
('home_briefs.runtime_columns','home_briefs','0258_home_briefs_kind.sql','kind,handled,delivered_at'),
('routine_runs','routine_runs','0259_routine_schedules.sql',''),
('family_automation_rules.runtime_columns','family_automation_rules','0259_routine_schedules.sql','schedule_kind,schedule_expr,anchor_key,offset_days,at_hour,next_run_at,said,source_request_id'))
SELECT e.label,e.migration,to_regclass('public.'||quote_ident(e.table_name)) IS NOT NULL AS table_present,
  CASE WHEN e.columns='' THEN ARRAY[]::text[] ELSE ARRAY(SELECT wanted.name FROM unnest(string_to_array(e.columns,',')) AS wanted(name) WHERE NOT EXISTS(SELECT 1 FROM information_schema.columns c WHERE c.table_schema='public' AND c.table_name=e.table_name AND c.column_name=wanted.name)) END AS missing_columns
FROM expected e ORDER BY e.label;
